### ISSUE TITLE
[1.16] Unknown server crash

### ISSUE THREAD

**Issue by Wu4410** [Loli-Server/LoliServer1.16#101]
I don’t know why, it crashed as soon as I logged in to the server, and the following message popped up in the control bar,Hope to get help.

[crash-2021-07-31_21.12.33-server.txt](https://github.com/Loli-Server/LoliServer1.16/files/6911226/crash-2021-07-31_21.12.33-server.txt)

**Comment by Kotori0629** [comment]
How can i repeat this crash?

**Comment by Kotori0629** [comment]
Try open "removeErrorEntities" in ../world/serverconfig/forge-server.toml
