### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by windwife** [Loli-Server/LoliServer1.16#104]
![微信图片_20210806095229](https://user-images.githubusercontent.com/88521141/128446321-5b823691-361b-4fd4-b013-cb4e552f05d6.png)
![微信图片_20210806095346](https://user-images.githubusercontent.com/88521141/128446329-af8a3963-99d0-4b90-90b4-a9cc0d919d57.png)
[crash-2021-08-06_10.07.50-server.txt](https://github.com/Loli-Server/LoliServer1.16/files/6942595/crash-2021-08-06_10.07.50-server.txt)
The crash report is at the catalog,when a player login the server,the server will crash and tell me the problem is:internal server error.

**Comment by Kotori0629** [comment]
Caused by: java.nio.file.FileSystemException: .\world\serverconfig\champions-ranks.toml: 另一个程序正在使用此文件，进程无法访问。
