### ISSUE TITLE
请修复构建服务器

### ISSUE THREAD

**Issue by 3269199948** [Loli-Server/LoliServer1.16#105]
如题

**Comment by Kotori0629** [comment]
已经恢复三天了

**Comment by 3269199948** [comment]
> 已经恢复三天了

那能否弄一个最新的服务器版本放到这里

**Comment by Kotori0629** [comment]
> > 已经恢复三天了
> 
> 那能否弄一个最新的服务器版本放到这里

启用loliserver.yml中的check-update， 将会自动下载最新版本核心
