### ISSUE TITLE
How to download that kernel and where?

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#111]
How to download that kernel and where? The new version, I don't know how to build it.

**Comment by MrJorman** [comment]
pls fix start mod "Infernal Expansion" !!!

**Comment by Kotori0629** [comment]
Set check-update to true, auto download .

**Comment by Kotori0629** [comment]
> pls fix start mod "Infernal Expansion" !!!

This is planned in the update
