### ISSUE TITLE
[BUG 1.16.5] infernal expansion no starting

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#112]
Minecraft Version(我的世界版本) : 1.16.5
LoliServer buildVersion(构建版本) : Provide LoliServer buildVersion: "LoliServer-1.16.5-50-server.jar"

MOD: infernal expansion
Logs : https://paste.ubuntu.com/p/X4jCnqjGbd/

Steps to Reproduce(复现步骤) :

Install my mods and run server

**Comment by XionioXMaster** [comment]
Stop flooding topics, have respect for the author of loli!

**Comment by Kotori0629** [comment]
#96 Duplicate

**Comment by Kotori0629** [comment]
This is planned in the update

**Comment by MrJorman** [comment]
> This is planned in the update

can you fix it now? I can deposit$5

**Comment by Kotori0629** [comment]
No, I can't build a development environment. We don't accept donations in any way

**Comment by MrJorman** [comment]
I need fix start mod Infernal Expansion

**Comment by XionioXMaster** [comment]
> I need fix start mod Infernal Expansion

clown

**Comment by MrJorman** [comment]
> > I need fix start mod Infernal Expansion

you clown

**Comment by MrJorman** [comment]
is it really so difficult to fix this error? I have already been sitting for more than 2 weeks waiting..

**Comment by Kotori0629** [comment]
> 
> 
> is it really so difficult to fix this error? I have already been sitting for more than 2 weeks waiting..

If my development environment worked properly, this error would have been fixed long ago

**Comment by MrJorman** [comment]
> > is it really so difficult to fix this error? I have already been sitting for more than 2 weeks waiting..
> 
> If my development environment worked properly, this error would have been fixed long ago

please. please try to fix it.. very necessary.

**Comment by XionioXMaster** [comment]
> > > is it really so difficult to fix this error? I have already been sitting for more than 2 weeks waiting..
> > 
> > 
> > If my development environment worked properly, this error would have been fixed long ago
> 
> please. please try to fix it.. very necessary.

clown

**Comment by MrJorman** [comment]
No fixed.
