### ISSUE TITLE
No working TAB plugin

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#114]
Install TAB Plugin and check.

**Comment by Kotori0629** [comment]
Download link?

**Comment by MrJorman** [comment]
https://disk.yandex.ru/d/9ftFVxRGUf8Elw

**Comment by Kotori0629** [comment]
logs ?

**Comment by XionioXMaster** [comment]
I suggest closing such topics, it is not respectful to create such topics!

**Comment by Kotori0629** [comment]
This plugin work in LoliServer, check you depends
