### ISSUE TITLE
进入下界后短时间内服务器崩溃

### ISSUE THREAD

**Issue by Tuskaa** [Loli-Server/LoliServer1.16#116]
**Minecraft Version(我的世界版本) :1.16.5

**LoliServer buildVersion(构建版本) :LoliServer-1.16.5-50-server

**Operating System(操作系统) :Windows Server 2012 R2 (amd64) version 6.3

**Logs :https://paste.ubuntu.com/p/MqffsMhfyG/

**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list(插件列表) :完全纯净

**Description of issue(描述) :
进入地狱后停留1分钟左右服务器就会崩溃炸服，尝试过换java版本和游戏内清除地狱生物，依然都会崩溃。
远程主机曾装过java16和开启1.18快照服务器后，才开始崩溃，在这之前并没有问题。

**Comment by Kotori0629** [comment]
#108 重复 ， 仇恨问题
