### ISSUE TITLE
[BUG 1.16.5] The axe for private does not work

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#118]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** build 55

**Operating System(操作系统) :** Windows 10 (64 bit)

**Logs :** no logs

**Mod list(模组列表) :** Abnormals+Aurora mods

**Plugin list(插件列表) :** https://paste.ubuntu.com/p/VryBXfHG8Y/

**Description of issue(描述) :** When a player wants to make a private using the WorldEdit/WorldGuard plugin and crafts a wooden axe or gets it through / / wand, it feels like his rights are flying off and he just doesn't want to privatize the axe, but this is corrected if you re-upload to the server.. this was not the case on other cores.

**Comment by Kotori0629** [comment]
I think you should tell someone to stop modifying PlayerList and ServerPlayerEntity

**Comment by MrJorman** [comment]
> I think you should tell someone to stop modifying PlayerList and ServerPlayerEntity

you don't fix anything in your core, it's very terribly bug-ridden to the point of horror..

**Comment by MrJorman** [comment]
> I think you should tell someone to stop modifying PlayerList and ServerPlayerEntity

you're a good guy and smart, but all people are lazy, I know that, but I removed your core for a reason-a lot of hard bugs, dupes..

**Comment by MrJorman** [comment]
> I think you should tell someone to stop modifying PlayerList and ServerPlayerEntity

Oh, sorry, I thought you were telling me to stop changing players, I think I misunderstood you, sorry, I was wrong)

**Comment by XionioXMaster** [comment]
If you use LuckyPerms on your server, after saving the rights, the player must re-enter the server to update them, which is why the right did not work immediately after it was added to the server.
