### ISSUE TITLE
[BUG 1.16.5] The armor stand does not drop the worn armor

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#119]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : build 55

Operating System(操作系统) : Windows 10 (64 bit)

Logs : no logs

Mod list(模组列表) : Abnormals+Aurora mods

Plugin list(插件列表) : https://paste.ubuntu.com/p/VryBXfHG8Y/

Description of issue(描述) : Take the armor rack, put the armor on it and break it - the worn armor will not fall out.

**Comment by XionioXMaster** [comment]
https://user-images.githubusercontent.com/86433158/130110689-e0c69949-71d5-4989-9c27-574e24b552a9.mp4

I managed to reproduce!

I also remembered that Mohist has a fix for this change, I suppose you can look at it superficially
https://github.com/MinecraftMist/Mist/commit/7418e0c3268ce237eefadf617ebea518090a42c3
