### ISSUE TITLE
[BUG 1.16.5] When a player enters the ender world - crash server

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#121]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : build 55

Operating System(操作系统) : Windows 10 (64 bit)

Logs : https://paste.ubuntu.com/p/gv6r5tQGDN/

Mod list(模组列表) : Repurposed Structures + abnormals mods + auroramods + quark

Plugin list(插件列表) : https://paste.ubuntu.com/p/VryBXfHG8Y/

Description of issue(描述) : When a player enters the world_the_end - crash, or when he teleports using commands from the ordinary world to a player who is in the world_the_end - crash.

**Comment by XionioXMaster** [comment]
I cannot reproduce this on a clean loli

**Comment by MrJorman** [comment]
Mod: Repurposed Structures

**Comment by MrJorman** [comment]
[crash-2021-08-20_03.10.31-server.txt](https://github.com/Loli-Server/LoliServer1.16/files/7019705/crash-2021-08-20_03.10.31-server.txt)

**Comment by KomiMoe** [comment]
please make sure your mods up to date.

**Comment by MrJorman** [comment]
i use last update. no working.

**Comment by MrJorman** [comment]
fix.
