### ISSUE TITLE
[1.16] Create mod crash

### ISSUE THREAD

**Issue by bigenergy** [Loli-Server/LoliServer1.16#123]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : build 57

Operating System(操作系统) : ubuntu

Logs : no logs

Mod list(模组列表) : Create

Plugin list(插件列表) : https://paste.ubuntu.com/p/5M57JqYsmP/

**Comment by XionioXMaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/create/files/3419412

Use the last version, there are many fixes out there
