### ISSUE TITLE
[BUG 1.16.5] DUPE BED WorldGuard

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#128]
DUPE BED WorldGuard

when I put the bed in private, there is a second hitbox of this bed and it can be broken by a player and this is a dupe bed.

**Comment by XionioXMaster** [comment]
It cannot be reproduced, it can be closed. No additional information!

**Comment by XionioXMaster** [comment]
https://user-images.githubusercontent.com/86433158/132648624-b43231b3-c978-4ab6-aeec-ba6b6cee3479.mp4
