### ISSUE TITLE
[1.16] oh-the-biomes-youll-go crash

### ISSUE THREAD

**Issue by bigenergy** [Loli-Server/LoliServer1.16#131]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-60-server.jar"

**Operating System(操作系统) :** ubuntu

**Concerned mod / plugin(有关的插件/Mod) :** https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go (version 1.3.2)

**Logs :** [crash-2021-08-27_20.09.54-server.txt](https://github.com/Loli-Server/LoliServer1.16/files/7068569/crash-2021-08-27_20.09.54-server.txt) (https://pastebin.com/haJruDKB)

**Steps to Reproduce(复现步骤) :**
 1. install byg 1.3.2
 2. server crash

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/132997661-e36c5565-f3e2-45b4-a8cc-432721d9fac3.png)
No reproduce
