### ISSUE TITLE
[1.16] Flan mod crash

### ISSUE THREAD

**Issue by bigenergy** [Loli-Server/LoliServer1.16#132]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-60-server.jar"

**Operating System(操作系统) :** ubuntu

**Concerned mod / plugin(有关的插件/Mod) :** https://www.curseforge.com/minecraft/mc-mods/flan-forge

**Logs :** https://pastebin.com/DMA4gZ2x and https://pastebin.com/3KKbjdU1

**Steps to Reproduce(复现步骤) :**
 1. Install https://www.curseforge.com/minecraft/mc-mods/flan-forge
 2. Run server
 3. Crash https://pastebin.com/DMA4gZ2x and https://pastebin.com/3KKbjdU1

**Comment by XionioXMaster** [comment]
**Sorry, I already reported this**
https://github.com/Loli-Server/LoliServer1.16/issues/91
