### ISSUE TITLE
[BUG 1.16.5] SERVER CRASH WHEN CHUNKS LOADING..

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#135]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 55

**Operating System(操作系统) :** Windows 10 (64bit)

**Logs :** https://pastebin.com/fVPWTN3u

**Mod list(模组列表) :** 

**Plugin list(插件列表) :** 

**Description of issue(描述) :** server crash.. when chunks loading..

**Comment by Kotori0629** [comment]
Try JDK8?

**Comment by MrJorman** [comment]
11
