### ISSUE TITLE
[1.16.5 BUG] Quark BackPack - duping resources

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#138]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** latest

**Operating System(操作系统) :** Windows 10

**Logs :** https://pastebin.com/mQiRWrbV

**Mod list(模组列表) :** Quark & QuarkOddities

**Plugin list(插件列表) :** 

**Description of issue(描述) :** When I try to craft with a backpack on, and they pull an item out of the craft - it multiplies, this is a bug. Please fix it.

**Comment by Kotori0629** [comment]
Does not work in this commit ?

**Comment by Kotori0629** [comment]
Try to use latestVersion: [1.16.5-65](http://nat.loliidc.cn:33644/job/LoliServer1.16/lastSuccessfulBuild/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-65-server.jar)

**Comment by MrJorman** [comment]
yes, i use 65 build

**Comment by MrJorman** [comment]
The error is also relevant, players multiply resources through inventory with a backpack on.

**Comment by MrJorman** [comment]
1. put on a backpack
2. open the inventory
3. Put any item in the crafting slot, pick it up and get two items, as well as a crash log

**Comment by MrJorman** [comment]
1. put on a backpack
2. open the inventory
3. Put any item in the crafting slot, pick it up and get two items, as well as a crash log
