### ISSUE TITLE
[BUG 1.16.5] WorldBorder world_the_end, world_nether no saving from restart server..

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#139]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : latest

Operating System(操作系统) : Windows 10

Logs : none

Mod list(模组列表) : no mods

Plugin list(插件列表) : no plugins

Description of issue(描述) : when I set the border of the world in the worlds, it disappears in hell and in the edge after restarting the server..

**Comment by Kotori0629** [comment]
Use latestVerison? Try to use latestVersion: [1.16.5-65](http://nat.loliidc.cn:33644/job/LoliServer1.16/lastSuccessfulBuild/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-65-server.jar)

**Comment by MrJorman** [comment]
i use latest version.. no working..

**Comment by XionioXMaster** [comment]
Everything works great for me! Perhaps your server crashes due to a lack of RAM, which is why saving does not work. This is the only way I was able to find out that the server does not save the loaded world.
