### ISSUE TITLE
[1.16] Autum 2 needs additional fix 

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#140]
Minecraft Version(我的世界版本) : 1.16

LoliServer buildVersion(构建版本) : "LoliServer-1.16.5-57-server.jar"

Operating System(操作系统) : unbuntu 20

Concerned mod / plugin(有关的插件/Mod) : I'm tested only Autum 2 But there may be others in the log, since it was from the server

Logs : https://paste.ubuntu.com/p/TCQN8x8nyh/

Steps to Reproduce(复现步骤) :

Past fix needs additional code
https://github.com/Loli-Server/LoliServer1.16/issues/127

**Comment by XionioXMaster** [comment]
https://github.com/MohistMC/Mohist/issues/1712

**Comment by Kotori0629** [comment]
How can I repeat this question？

**Comment by Kotori0629** [comment]
Latest Successful build version : 1.16.5-65

**Comment by Kotori0629** [comment]
This problem fix in version: 1.16.5-60

**Comment by Kotori0629** [comment]
After using the latest version, has this problem been solved？

**Comment by XionioXMaster** [comment]
> After using the latest version, has this problem been solved？ @XionioXMaster

Now I'll check it out

**Comment by XionioXMaster** [comment]
> After using the latest version, has this problem been solved？ @XionioXMaster

I can't check if the Loli libraries are broken again

**Comment by Kotori0629** [comment]
Delete libraries/ , re-download

**Comment by XionioXMaster** [comment]
> Delete libraries/ , re-download
can you give a link to build 60?

**Comment by Kotori0629** [comment]
> > Delete libraries/ , re-download
> 
> can you give a link to build 60?

http://nat.loliidc.cn:33644/job/LoliServer1.16/60/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-60-server.jar

**Comment by XionioXMaster** [comment]
> > > Delete libraries/ , re-download
> > 
> > 
> > can you give a link to build 60?
> 
> http://nat.loliidc.cn:33644/job/LoliServer1.16/60/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-60-server.jar

Yes, I do not notice departures

**Comment by Kotori0629** [comment]
> > > > Delete libraries/ , re-download
> > > 
> > > 
> > > can you give a link to build 60?
> > 
> > 
> > http://nat.loliidc.cn:33644/job/LoliServer1.16/60/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-60-server.jar
> 
> Yes, I do not notice departures

So this problem has been fixed?

**Comment by XionioXMaster** [comment]
> > > > > Delete libraries/ , re-download
> > > > 
> > > > 
> > > > can you give a link to build 60?
> > > 
> > > 
> > > http://nat.loliidc.cn:33644/job/LoliServer1.16/60/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-60-server.jar
> > 
> > 
> > Yes, I do not notice departures
> 
> So this problem has been fixed?

yes, apparently I missed the moment with the editing, the fix is ​​successful!

**Comment by Kotori0629** [comment]
> > > > > > Delete libraries/ , re-download
> > > > > 
> > > > > 
> > > > > can you give a link to build 60?
> > > > 
> > > > 
> > > > http://nat.loliidc.cn:33644/job/LoliServer1.16/60/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-60-server.jar
> > > 
> > > 
> > > Yes, I do not notice departures
> > 
> > 
> > So this problem has been fixed?
> 
> yes, apparently I missed the moment with the editing, the fix is ​​successful!

Okay. I close you pull request.
