### ISSUE TITLE
/gradlew LoliServerJar don't work?

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#144]
Can't create server .jar using / gradlew LoliServerJar https://github.com/XionioXMaster/LoliServer1.16/actions/runs/1203457313

Or am I doing something wrong? Can you describe how to assemble it correctly?

**Comment by Kotori0629** [comment]
You deleted something important

**Comment by Kotori0629** [comment]
I think you not run : ./gradlew setup

**Comment by Kotori0629** [comment]
- name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew setup
        ./gradlew genPatches

**Comment by Kotori0629** [comment]
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew setup
        ./gradlew genPatches
        ./gradlew LoliServerJar

**Comment by XionioXMaster** [comment]
> jobs:
> build:
> 
> ```
> runs-on: ubuntu-20.04
> 
> steps:
> - uses: actions/checkout@v1
> - name: Set up JDK 1.8
>   uses: actions/setup-java@v1
>   with:
>     java-version: 1.8
> - name: Build with Gradle
>   run: |
>     chmod +x ./gradlew
>     ./gradlew setup
>     ./gradlew genPatches
>     ./gradlew LoliServerJar
> ```

https://github.com/XionioXMaster/MIA/runs/3521601818?check_suite_focus=true  Still a mistake((
https://github.com/XionioXMaster/MIA/blob/1.16.5/.github/workflows/gradle.yml

**Comment by Kotori0629** [comment]
> > jobs:
> > build:
> > ```
> > runs-on: ubuntu-20.04
> > 
> > steps:
> > - uses: actions/checkout@v1
> > - name: Set up JDK 1.8
> >   uses: actions/setup-java@v1
> >   with:
> >     java-version: 1.8
> > - name: Build with Gradle
> >   run: |
> >     chmod +x ./gradlew
> >     ./gradlew setup
> >     ./gradlew genPatches
> >     ./gradlew LoliServerJar
> > ```
> 
> https://github.com/XionioXMaster/MIA/runs/3521601818?check_suite_focus=true Still a mistake((
> https://github.com/XionioXMaster/MIA/blob/1.16.5/.github/workflows/gradle.yml

So.. I say don't use Github Action to build......

**Comment by XionioXMaster** [comment]
> > > jobs:
> > > build:
> > > ```
> > > runs-on: ubuntu-20.04
> > > 
> > > steps:
> > > - uses: actions/checkout@v1
> > > - name: Set up JDK 1.8
> > >   uses: actions/setup-java@v1
> > >   with:
> > >     java-version: 1.8
> > > - name: Build with Gradle
> > >   run: |
> > >     chmod +x ./gradlew
> > >     ./gradlew setup
> > >     ./gradlew genPatches
> > >     ./gradlew LoliServerJar
> > > ```
> > 
> > 
> > https://github.com/XionioXMaster/MIA/runs/3521601818?check_suite_focus=true Still a mistake((
> > https://github.com/XionioXMaster/MIA/blob/1.16.5/.github/workflows/gradle.yml
> 
> So.. I say don't use Github Action to build......

And how do you assemble?

**Comment by Kotori0629** [comment]
> > > > jobs:
> > > > build:
> > > > ```
> > > > runs-on: ubuntu-20.04
> > > > 
> > > > steps:
> > > > - uses: actions/checkout@v1
> > > > - name: Set up JDK 1.8
> > > >   uses: actions/setup-java@v1
> > > >   with:
> > > >     java-version: 1.8
> > > > - name: Build with Gradle
> > > >   run: |
> > > >     chmod +x ./gradlew
> > > >     ./gradlew setup
> > > >     ./gradlew genPatches
> > > >     ./gradlew LoliServerJar
> > > > ```
> > > 
> > > 
> > > https://github.com/XionioXMaster/MIA/runs/3521601818?check_suite_focus=true Still a mistake((
> > > https://github.com/XionioXMaster/MIA/blob/1.16.5/.github/workflows/gradle.yml
> > 
> > 
> > So.. I say don't use Github Action to build......
> 
> And how do you assemble?

I'm not use Github Action.....I choosed Jenkins
