### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by Dokman** [Loli-Server/LoliServer1.16#145]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Latest Commit

**Operating System(操作系统) :** Windows

**Logs :**  [Link](https://pastebin.com/CWpLE3wW)

**Mod list(模组列表) :** No

**Plugin list(插件列表) :** No

**Description of issue(描述) :** Cannot compile on Java JDK 8

**Comment by Kotori0629** [comment]
Try to use JDK1.8.0_291 or AdoptOpenJDK

**Comment by Dokman** [comment]
fixed with AdoptOpenJDK
