### ISSUE TITLE
[1.16] Curios mod - The problem of his inventory after the death of a player

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#149]
**Minecraft Version(我的世界版本) :** 1 16 5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-67-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** In the video below, there are no plugins! Pure test

**Logs :** Nope

**Steps to Reproduce(复现步骤) :**
 1. After the death of the player, the Curios inventory no longer works, I tested it without plugins on the server, however, moving to another world, you can restore access again!
 2. Video: https://youtu.be/R4yeNDH-8vQ

**Comment by Kotori0629** [comment]
Yes yes. I'm dealing with him, but unfortunately, this problem is quite difficult to deal with
