### ISSUE TITLE
[1.16] Eidolon and citadel cause problems in recent versions of Loli

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#151]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-72-server.jar"

**Operating System(操作系统) :** unbuntu 20

**Concerned mod / plugin(有关的插件/Mod) :** Alex Mobs, Citadel, Eidolon

**Logs :** https://paste.loliidc.cn/?8278f2382b6d47fb#9AhnbQ7wx5tHk6mSjnedGHUXkpsXAvvT845pRCNmGGfP

**Steps to Reproduce(复现步骤) :**
 1. After the player dies, he cannot revive himself, after pressing the respawn button, the console writes about an error on the side of Eidolon, first I wrote about this to the author of Citadel, he pointed out the error of Eidolon, The author of Eidolon said that this is most likely on the side of loliserver and not will try to fix it until he hears it This is the reason in Eidolon
Please note that there was no such error before, it occurred to me when deleting the World folder and updating to the latest version
2. 

**Description of issue :** To reproduce this bug, you need to die 2-3 times

**Comment by Kotori0629** [comment]
这和你上次提交的是同一个问题, 正在修复.....

**Comment by XionioXMaster** [comment]
> 这和你上次提交的是同一个问题, 正在修复.....



> 这和你上次提交的是同一个问题, 正在修复.....

对不起，我糊涂了

**Comment by Kotori0629** [comment]
> > 这和你上次提交的是同一个问题, 正在修复.....
> 
> 对不起，我糊涂了

暂时先回滚使用1.16.5-67以前的版本，

**Comment by DonorKrovi** [comment]
> > > 这和你上次提交的是同一个问题, 正在修复.....
> > 
> > 
> > 对不起，我糊涂了
> 
> 暂时先回滚使用1.16.5-67以前的版本，

I have the same problem, thanks for specifying the version to rollback. Love your core
and you)

**Comment by DonorKrovi** [comment]
but 67 build not fix this

**Comment by Kotori0629** [comment]
> but 67 build not fix this

Before 67
