### ISSUE TITLE
[1.16] Horrible CMI plugin lagbacks when going to chunk

### ISSUE THREAD

**Issue by DonorKrovi** [Loli-Server/LoliServer1.16#152]
**Minecraft Version(我的世界版本) :** Minecraft version

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-72-server.jar"

**Operating System(操作系统) :** Windows 10

**Concerned mod / plugin(有关的插件/Mod) :** BetterEnd, Quark 
Plugins: CMI 9 0 2 9, CMILib
[archive-2021-09-09T095235+0200.tar.gz](https://github.com/Loli-Server/LoliServer1.16/files/7134592/archive-2021-09-09T095235%2B0200.tar.gz)

**Logs :** Nope

**Steps to Reproduce(复现步骤) :**
 1. As soon as I set / cmi setspawn in the world and restart the server, there are terrible drawdowns in the area where the spawn is

**Comment by XionioXMaster** [comment]
Now I will try to reproduce

**Comment by XionioXMaster** [comment]
Can not reproduce
