### ISSUE TITLE
[1.16] Plugin Oh The Dungeon. Works but reproduces launch with errors!

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#160]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-77-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** Only OhTheDungeon.jar [Архив ZIP - WinRAR.zip](https://github.com/Loli-Server/LoliServer1.16/files/7155847/ZIP.-.WinRAR.zip)

**Logs :** https://paste.loliidc.cn/?d0f79807b2ace7c2#56mDX9mLecA1q2RMeCbW37m4GGi5XRVUjJzY3hMwU8e6

**Steps to Reproduce(复现步骤) :**
 1. Start the server with this plugin, it will start successfully, but errors may occur during the process

**Comment by Kotori0629** [comment]
Fixed, wait update
