### ISSUE TITLE
[1.16] Conflict between mod and plugins

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#161]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-77-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** ProtocolLib 1.16.5 plugin + FartherViewDistance 6.0.4 plugin + Infernal Expansion 2.2.0 Mod
Fast dowload: 
[Архив ZIP - WinRAR.zip](https://github.com/Loli-Server/LoliServer1.16/files/7156048/ZIP.-.WinRAR.zip) Mods
[Архив ZIP - WinRAR.zip](https://github.com/Loli-Server/LoliServer1.16/files/7156052/ZIP.-.WinRAR.zip) Plugins

**Logs :** https://paste.loliidc.cn/?11034531cbcd7171#8VMywNSgwkBiy8rWq6jigZddpQNmBpJd2VxgX4g7g7L8

**Steps to Reproduce(复现步骤) :**
 1. If you use this mod and plugin together on the server there will be conflicts, as soon as you log into the server you will receive spam in the console with errors!

**Comment by Kotori0629** [comment]
This is not a conflict! This is probably caused by my misoperation! If it's convenient, please help me test which version started this error

**Comment by XionioXMaster** [comment]
> This is not a conflict! This is probably caused by my misoperation! If it's convenient, please help me test which version started this error



> This is not a conflict! This is probably caused by my misoperation! If it's convenient, please help me test which version started this error

I do not fully understand which version are you talking about? About the loliserver version?

**Comment by XionioXMaster** [comment]
> Yes, test the beginning version of this error

https://github.com/Loli-Server/LoliServer1.16/commit/535da70fbf339bab567f9f3bace3f13db146554c
I'll start from the very beginning, that is, when you fixed the mod, the assembly was at number 52
http://nat.loliidc.cn:33644/job/LoliServer1.16/52/

**Comment by XionioXMaster** [comment]
http://nat.loliidc.cn:33644/job/LoliServer1.16/55/

And so 54 did not start correctly, but I saw that it was fixed in 55, build 55 has this problem at launch

https://paste.loliidc.cn/?1900ab97dcdb22fa#E2Nz9MroekV2oqLQ4QXGpDyW1htt2syz2x1pKNZB7QGK

**Comment by Kotori0629** [comment]
Install Infernal Expansion , this problem reproduce

**Comment by XionioXMaster** [comment]
> Install Infernal Expansion , this problem reproduce

If you install only this mod without ProtocolLib everything works fine! But as soon as you return ProtocolLib when logging into the server, there will be errors that I provided above

**Comment by Kotori0629** [comment]
yes yes> > Install Infernal Expansion , this problem reproduce
> 
> 
> 
> If you install only this mod without ProtocolLib everything works fine! But as soon as you return ProtocolLib when logging into the server, there will be errors that I provided above

**Comment by Luohuayu** [comment]
不要相信维恩的

**Comment by DonorKrovi** [comment]
This FIx?

**Comment by XionioXMaster** [comment]
> This FIx?

no
