### ISSUE TITLE
invalid payload REGISTER when joining my server with mods

### ISSUE THREAD

**Issue by Xplodin** [Loli-Server/LoliServer1.16#165]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 77

**Operating System(操作系统) :** Ubuntu 18.04
**Logs :** {Link(s) of logs and crash reports if you have}, (https://paste.loliidc.cn)

There isnt much I could dig up except:
 Couldnt register custom payload
>.... [04:50:40][Server thread][INFO]: *** lost connection: Invalid payload REGISTER!
>.... [04:50:41][Server thread][INFO]: *** left the game

**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
[betterdungeons, kubejs, quarryplus, supermartijn642configlib, alexsmobs, lazierae2, variant16x, integratedterminals, draconicevolution, uppers, rad, javd, gamemenuremovegfarb, mcwwindows, envirocore, silents_mechanisms, bambooeverything, modnametooltip, pitg, thermal, bettercaves, essentials, ironjetpacks, rftoolsbase, forgeendertech, gravelminer, ctm, ravageandcabbage, xnet, materialis, farmersdelightintegrations, yungsapi, powah, cabletiers, rangedpumps, environmental, shrink, wstweaks, xreliquary, atum, randompatches, apotheosis, darkutils, speedyhoppers, dynview, tmechworks, mysticalagradditions, supplementaries, refinedstorage, betterendforge, upgradednetherite, easy_piglins, structure_gel, ratlantis, industrialforegoing, cleancut, torchmaster, repurposed_structures, thermal_innovation, botanytrees, ironfurnaces, dungeons_plus, mcwtrpdoors, silentgear, supermartijn642corelib, extcaves, betterdefaultbiomes, cb_multipart, botania, sf, spark, itemstitchingfix, mysticaladaptations, portality, cb_microblock, curios, randomite, extlights, topaddons, yungsextras, framedblocks, angelring, thermal_foundation, tombstone, fertilization, integratednbt, extrastorage, thermal_locomotion, naturesaura, constructionwand, mcwroofs, cfm, observerlib, mcwfurnitures, globalxp, cloth-config, the_bumblezone, betterburning, charm, toms_storage, fastleafdecay, codechickenlib, bettermineshafts, geckolib3, tconplanner, passthroughsigns, quarkoddities, nomowanderer, craftandhunt, ftblibrary, woot, jei, attributefix, tesseract, mekanism, caelus, upgrade_aquatic, ringsofascension, invtweaks, naturescompass, libx, compactmachines, stoneholm, botanypots, adhooks, phosphophyllite, engineerstools, farmingforblockheads, pneumaticcraft, cofh_core, snowundertrees, endergetic, pedestals, travellersboots, environmentalcreepers, iceandfire, plonk, ars_nouveau, mysticalworld, extradisks, rftoolspower, immersivepetroleum, crossroads, forge, mythicbotany, integratedcrafting, minecraft, logprot, theoneprobe, ftbquests, psi, immersiveengineering, tinker_rapier, pamhc2crops, ceilingtorch, backpacker, dimdungeons, rftoolsbuilder, pipez, flywheel, mantle, savageandravage, xaerominimap, integrateddynamics, pamhc2foodcore, itemcollectors, ftbbackups, rats, dragonseeker, autumnity, polymorph, autoreglib, securitycraft, integratedterminalscompat, backpacked, pickletweaks, fastfurnace, appleskin, integratedtunnelscompat, lootr, connectedglass, refinedrelocation, durabilityviewer, damagetilt, byg, aquaculture, cosmeticarmorreworked, lootbagmod, rsrequestify, cyclopscore, blue_skies, astralsorcery, advancedperipherals, aiotbotania, tinyredstone, eidolon, managear, curiousshulkerboxes, kleeslabs, findme, rsgauges, furnacemk2, glassential, envirotech, xaeroworldmap, cookingforblockheads, placebo, dankstorage, citadel, iafgear, culinaryconstruct, bookshelf, sophisticatedbackpacks, uteamcore, buildinggadgets, mcwdoors, mekanismgenerators, maessentials, xnetgases, omnis, ftbteams, dummmmmmy, twilightforest, mob_grinding_utils, experiencebugfix, rsinfinitybooster, prettypipes, chocolate, mcwbridges, farmersdelight, usefulbackpacks, entangled, commoncapabilities, crashutilities, mekanismadditions, valkyrielib, lollipop, ftbranks, mcwfences, mining_dimension, simplylight, jousting, bountiful, cnb, solarflux, goprone, dpanvil, patchouli, rftoolsstorage, oreexcavation, tiab, rftoolscontrol, thermal_expansion, integratedtunnels, elevatorid, gunpowderlib, betterstrongholds, expandedstorage, enigmaticlegacy, runelic, mekanismtools, architectury, psipherals, curiouselytra, computercraft, compactcrafting, productivebees, trashcans, smallships, bwncr, servertabinfo, gamemenumodoption, quantumstorage, cyclic, rhino, botaniaadditions, ma-enchants, biggerreactors, cucumber, trashslot, pamhc2trees, buzzier_bees, flatbedrock, itemfilters, elementalcraft, metalbarrels, druidcraft, abnormals_core, scannable, ae2extras, create, waystones, clumps, comforts, appliedenergistics2, cb_multipart_minecraft, dimstorage, outer_end, bno, vanillatweaks, taffyjump, dungeoncrawl, demagnetize, travel_anchors, lazydfu, mcjtylib, integrateddynamicscompat, blockswap, mininggadgets, enderstorage, akashictome, ftbchunks, bloodmagic, scuba_gear, fasterladderclimbing, brandonscore, immersiveposts, selene, mysticalagriculture, sounddeviceoptions, craftingtweaks, tconstruct, rftoolsutility, enchdesc, toolbelt, titanium, mana-and-artifice, compactores, silentlib, forbidden_arcanus, fluidtank, atmospheric, enviroenergy, easy_villagers, quark, fastbench, storagedrawers, fluxnetworks, inventoryhud, fins, ferritecore, engineersdecor, chisel, solcarrot, modularrouters, silentgems, refinedstorageaddons, overloadedarmorbar, chiselsandbits, morphtool, translocators, createaddition]
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
Unexpected exception while parsing console command "getpluginlist"
org.bukkit.command.CommandException: Unhandled exception executing 'getpluginlist' in moe.loliserver.command.GetPluginListCommand(getpluginlist)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:167) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:680) ~[forge:1.16.5-77]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:666) ~[forge:1.16.5-77]
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:362) ~[?:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:926) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -23
at java.lang.String.substring(String.java:1967) ~[?:1.8.0_292]
at moe.loliserver.legacy.util.HasteUtils.pasteUbuntu(HasteUtils.java:34) ~[forge:?]
at moe.loliserver.legacy.util.HasteUtils.pasteUbuntu(HasteUtils.java:12) ~[forge:?]
at moe.loliserver.command.GetPluginListCommand.execute(GetPluginListCommand.java:27) ~[forge:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[forge:?]
... 8 more

^^when running getpluginlist

BanItem
Clearlag
Clearlagtimer
Elitelootbox
essentials
holographics displays
luckperms
superbvote
ultimateautorestart
Vault
votifier
**Description of issue(描述) :** {Give all details about your issue}
attempt to join server but get connection closed with the above log

log is 30mb and cant upload but thats everything thats mentioned relating to the error

**Comment by Xplodin** [comment]
https://paste.loliidc.cn/?bd88bdc9b23723a5#2GeruMSeuripAQKUSjJ5bQAeMMAkbzUpAhRKwgWm4E94


got the log uploaded finally

**Comment by XionioXMaster** [comment]
> https://paste.loliidc.cn/?bd88bdc9b23723a5#2GeruMSeuripAQKUSjJ5bQAeMMAkbzUpAhRKwgWm4E94
> 
> got the log uploaded finally

I would advise you to remove 1 mod from the assembly until you find the problematic one!

Can you also provide a server log in .txt format? When I view the page I have terrible lags

**Comment by Xplodin** [comment]
> > https://paste.loliidc.cn/?bd88bdc9b23723a5#2GeruMSeuripAQKUSjJ5bQAeMMAkbzUpAhRKwgWm4E94
> > got the log uploaded finally
> 
> I would advise you to remove 1 mod from the assembly until you find the problematic one!
> 
> Can you also provide a server log in .txt format? When I view the page I have terrible lags

I cannot provide the log in txt as its still 40mb and will lag everywhere. The log is massive

**Comment by Kotori0629** [comment]
Re-upload logs

**Comment by Xplodin** [comment]
[debug.zip](https://github.com/Loli-Server/LoliServer1.16/files/7159003/debug.zip)
had to compress it because it was too large to upload

**Comment by Kotori0629** [comment]
Incomplete

**Comment by Xplodin** [comment]
> Incomplete

what is incomplete? thats the full debug.log that the server gave. server didnt crash or provide any error except that and reject clients using the same setup

**Comment by XionioXMaster** [comment]
> what is incomplete? thats the full debug.log that the server gave. server didnt crash or provide any error except that and reject clients using the same setup
That is why logs are often sent
Upload it to googl disk and drop it here

**Comment by Xplodin** [comment]
https://drive.google.com/file/d/1MQ3-7WqKt4v1dCK34l_UBL4KMTmQyTe8/view?usp=sharing

**Comment by Kotori0629** [comment]
I suggest checking your mod one by one
