### ISSUE TITLE
[1.16] Supplementaries blue bomb crash

### ISSUE THREAD

**Issue by bigenergy** [Loli-Server/LoliServer1.16#167]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-78-server.jar"

**Operating System(操作系统) :** ubuntu

**Concerned mod / plugin(有关的插件/Mod) :** https://www.curseforge.com/minecraft/mc-mods/supplementaries

**Logs :** https://pastebin.com/f5JLYghe or https://paste.loliidc.cn/?f4678430a47cfb2b#58SYc4NdP4efQD9Y1KMm1sgGmGmkumJvWzjJ2xUYBWt

**Steps to Reproduce(复现步骤) :**
 1. throw a blue bomb from supplementaries at the player
 2. crash server

**Comment by XionioXMaster** [comment]
Try to reproduce on pure Forge

**Comment by XionioXMaster** [comment]
> **Minecraft Version(我的世界版本) :** 1.16.5
> 
> **LoliServer buildVersion(构建版本) :** Provide LoliServer buildVersion: "LoliServer-1.16.5-78-server.jar"
> 
> **Operating System(操作系统) :** ubuntu
> 
> **Concerned mod / plugin(有关的插件/Mod) :** https://www.curseforge.com/minecraft/mc-mods/supplementaries
> 
> **Logs :** https://pastebin.com/f5JLYghe or https://paste.loliidc.cn/?f4678430a47cfb2b#58SYc4NdP4efQD9Y1KMm1sgGmGmkumJvWzjJ2xUYBWt
> 
> **Steps to Reproduce(复现步骤) :**
> 
> 1. throw a blue bomb from supplementaries at the player
> 2. crash server

I could not reproduce, everything works well for me. Latest Loli build


https://user-images.githubusercontent.com/86433158/133594728-4786c74b-9e39-4efe-9e27-5e59dff96bf4.mp4

**Comment by bigenergy** [comment]
the bomb should fly into the air, perhaps even into the unloaded chunk

**Comment by XionioXMaster** [comment]
> the bomb should fly into the air, perhaps even into the unloaded chunk

Demonstrate in the video, I didn't succeed.

**Comment by Luohuayu** [comment]
Report to mod author
