### ISSUE TITLE
服务器有时在自动保存时卡死

### ISSUE THREAD

**Issue by TCwater** [Loli-Server/LoliServer1.16#172]
**Minecraft Version(我的世界版本) :** {Minecraft version}
1.16.5
**LoliServer buildVersion(构建版本) :** {Provide LoliServer build number}
LoliServer-1.16.5-77-server.jar
**Operating System(操作系统) :** {Provide the name of your OS}
windows server 2019
**Logs :** {Link(s) of logs and crash reports if you have}, (https://paste.loliidc.cn)
https://paste.loliidc.cn/?fd2ff4a9be45c239#GpE83613eA2Sx9n5GnPFPoPcMjeCBStYfLHs72yccyk7
**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
• minecraft forge-1.16.5-36.2.4-server.jar : minecraft (1.16.5) - 1
• mods_folder [农夫乐事]FarmersDelight-1.16.5-0.4.5.jar : farmersdelight (1.16.5-0.4.5) - 1
• mods_folder [机械动力附加]create-stuff-additions1.16.5_v1.0.6.jar : create_stuff_additions (1.0.6) - 1
• mods_folder [玉] Jade-1.16.4-2.7.1.jar : jade (2.7.1) - 2
• mods_folder [皮肤]CustomSkinLoader_Forge-14.13-SNAPSHOT-199.jar : customskinloader (14.13-SNAPSHOT-199) - 1
• mods_folder debug-tools-2.0-SNAPSHOT.jar : debug-tools (NONE) - 1
• mods_folder [JEI物品管理器] jei-1.16.5-7.7.0.106.jar : jei (7.7.0.106) - 1
• mods_folder [女仆]LMRB-Forge-1.16.5-2.5.3.jar : littlemaidrebirth (2.5.3) - 1
• mods_folder [Crt魔改-机械动力]CreateTweaker-1.0.0.14.jar : createtweaker (1.0.0.14) - 1
• mods_folder spark-forge.jar : spark (1.4.3) - 1
• mods_folder [简单村民]easy_villagers-1.16.5-1.0.11.jar : easy_villagers (1.16.5-1.0.11) - 1
• mods_folder [机械动力前置]flywheel-1.16-0.1.1.jar : flywheel (1.16-0.1.1) - 1
• mods_folder [Curios API] curios-forge-1.16.5-4.0.5.2.jar : curios (1.16.5-4.0.5.2) - 1
• mods_folder [模块工具]tetra-1.16.5-3.14.1.jar : tetra (3.14.1) - 1
• mods_folder [机械动力]create-mc1.16.5_v0.3.2b.jar : create (v0.3.2b for 1.16.5) - 1
• mods_folder [模块工具前置]mgui-1.16.5-3.2.0.jar : mgui (3.2.0) - 1
• mods_folder [合成冲突修复]polymorph-forge-1.16.5-0.25.jar : polymorph (1.16.5-0.25) - 1
• mods_folder [抽屉]StorageDrawers-1.16.3-8.3.0.jar : storagedrawers (8.3.0) - 1
• mods_folder [末地重生]EndReborn+[0.8.4].jar : endreborn (0.8.4) - 1
• mods_folder [自定义三明治] culinaryconstruct-forge-1.16.5-4.0.0.6.jar : culinaryconstruct (1.16.5-4.0.0.6) - 1
• mods_folder [建筑之杖] constructionwand-1.16.5-2.2.jar : constructionwand (1.16.5-2.2) - 1
• mods_folder [猪灵AI]sapience-1.16.5-1.1.2.jar : sapience (1.1.2) - 1
• mods_folder [家具]cfm-7.0.0pre22-1.16.3.jar : cfm (7.0.0-pre22) - 1
• mods_folder [传送蛋糕]TelePastries-1.16.5-0.3.9.jar : telepastries (0.3.9) - 1
• mods_folder [沉浸附属]engineersdecor-1.16.4-1.1.14.jar : engineersdecor (1.1.14) - 1
• mods_folder [跳舞树]TwerkItMeal-1.3.8.jar : twerkitmeal (1.3.8) - 1
• mods_folder [魔改]CraftTweaker-1.16.5-7.1.0.320.jar : crafttweaker (7.1.0.320) - 1
• mods_folder [女仆]LMML-Forge-1.16.4-2.3.10.jar : littlemaidmodelloader (2.3.10) - 1
• mods_folder [沉浸原油]ImmersivePetroleum-1.16.5-3.3.0-5.jar : immersivepetroleum (3.3.0-5) - 1
• mods_folder [沉浸]Immersive Engineering.jar : immersiveengineering (1.16.5-5.0.2-137) - 1
• maven_libs forge-1.16.5-36.2.4-universal.jar : forge (36.2.4) - 1
• mods_folder [苹果皮]AppleSkin-mc1.16.2-forge-1.0.14.jar : appleskin (1.0.14) - 1
• mods_folder [更好的AI]WellBehavedMobs-v1.2.3-1.16.5.jar : wellbehavedmobs (1.2.3) - 1
• mods_folder [精致存储]refinedstorage-1.9.14.jar : refinedstorage (1.9.14) - 1
• mods_folder [简单猪灵]easy_piglins-1.16.5-1.0.0.jar : easy_piglins (1.16.5-1.0.0) - 1
• mods_folder [机械动力电力转换]createaddition-1.16.5-20210713a.jar : createaddition (1.16.5-20210713a) - 1
• mods_folder [机械动力护目镜]createplus-1.16.4_v0.3.2.1.jar : createplus (1.16.4_v0.3.2.1) - 1
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
FarmControl, PokemonAPI, JoinCommand, PlaceholderAPI, PluginManager, PlugMan, BaoZang, TabooLib5, Patch4, ConsoleSpamFix, NotBoom, NoRainReloaded, NBTAPI, WorldLevel, Shift_Menu, ItemDupeFix, MiniMOTD, LuckPerms, VoidGen, QiMengItemManage, Skript, ClearItem, CrazyAuctionsPlus, VillagerOptimiser, RandomCommand, AntiSpawner, ChatHelp, WGAcheck, GuiCommandBan, Fgive, AlwaysKeepInventory, ProtocolLib, LoginManager, Notbuild, LiteSignIn, ChineseCommand, OnlineReward, MiaoBoard, FairHunger, LimitPillagers, ActionAnnouncer, Vault, eBackup, DogHook, EntityTrackerFixer, PlayerPoints, LockettePro, PlayerTitle, RandomMoneyChat, WorldEdit, YukiNoaAPI, EvenMoreFish, AtMe, EasyDuels, MoneyDrop, BentoBox, AdvancedAchievements, ScriptBlockPlus, ItemBind, CratesLottery, SeekInventory, BanIt, BkyBlockEX, Multiverse-Core, Shopkeepers, Images, CatSeedLogin, QuickShop, CMILib, CMI, CMIEInjector, TrMenu
**Description of issue(描述) :** {Give all details about your issue}
服务器有时会在自动保存时卡死，使用bukkit里的autosave或者使用Skript里其他人写的自动保存脚本都会出现
Skript里其他人写的自动保存脚本https://paste.loliidc.cn/?7aa1294b32e6566a#HRmbZSEfxKtiAdvhREETy6TdVYnyM52BuS65nFm5TUDP

**Comment by Kotori0629** [comment]
你的Skript也只是定时执行save-all命令哇
