### ISSUE TITLE
[1.16] Create + GriefPrevention and incorrect operation of the deployer

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#174]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-80-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** Create + GriefPrevention
**Logs :** Nope

**Steps to Reproduce(复现步骤) :**
 1. deployer with create mod does not install blocks if using the GriefPrevention plugin
 2. 
![image](https://user-images.githubusercontent.com/86433158/133647722-28b6f6f4-c08c-4b1f-a2d0-c70554d09ba6.png)
![image](https://user-images.githubusercontent.com/86433158/133647775-930bb60e-7947-4dc7-ae37-98e4727175fa.png)

Everything works with WorldGuard! But GriefPrevention is better than WorldGuard

**Comment by XionioXMaster** [comment]
https://user-images.githubusercontent.com/86433158/133649138-d147363f-dae2-4441-be7f-e91ad2f9a6ef.mp4

**Comment by Kotori0629** [comment]
It feels like a FakePlayer permission problem

**Comment by XionioXMaster** [comment]
> It feels like a FakePlayer permission problem

If I understood you correctly this is because of the plugin

**Comment by XionioXMaster** [comment]
https://github.com/TechFortress/GriefPrevention/issues/1586
