### ISSUE TITLE
[1.16] Oh_the_dungeons_youll_go error

### ISSUE THREAD

**Issue by DonorKrovi** [Loli-Server/LoliServer1.16#179]
**Minecraft Version(我的世界版本) :** Minecraft version 1 16 5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-81-server.jar"

**Operating System(操作系统) :** Windows 10

**Concerned mod / plugin(有关的插件/Mod) :** Oh_the_dungeons_youll_go, more_structures mod, repurposedstructures mod, iceandfire mod,createaddition, create.

**Logs :** https://paste.loliidc.cn/?4273f1dd2fd56dfb#RMDe9EAQBmho4nwpTr22Fh4B5TAHi3sWg1iXk6uBzB2

**Steps to Reproduce(复现步骤) :**
 1. I turn on the server and suddenly some errors

**Comment by Kotori0629** [comment]
Repurposed Structures

**Comment by XionioXMaster** [comment]
> Repurposed Structures

It’s strange that it never happened before.
