### ISSUE TITLE
在启动下载资源时下载失败

### ISSUE THREAD

**Issue by 18210062927** [Loli-Server/LoliServer1.16#182]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 35

**Operating System(操作系统) :** windows 10 21H2

**Logs :**
PS C:\Users\Onlyacat233\Desktop\server> .\jdk-11.0.12\bin\java.exe -jar .\LoliServer-1.16.5-38-server.jar
.____          .__  .__  _________
|    |    ____ |  | |__|/   _____/ ______________  __ ___________
|    |   /  _ \|  | |  |\_____  \_/ __ \_  __ \  \/ // __ \_  __ \
|    |__(  <_> )  |_|  |/        \  ___/|  | \/\   /\  ___/|  | \/
|_______ \____/|____/__/_______  /\___  >__|    \_/  \___  >__|
        \/                     \/     \/                 \/
                             Welcome to LoliServer 1.16.5 ! - LoliServer Developement Group

[20:56:27][Loli/]: JAVA版本验证完成, LoliServer进程将继续进行
Global percentage >0%
Downloading file unsafe-0.2.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar failed :(
Global percentage >0%
Downloading file j2objc-annotations-1.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar failed :(
Global percentage >0%
Downloading file asm-commons-6.1.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/ow2/asm/asm-commons/6.1.1/asm-commons-6.1.1.jar failed :(
Global percentage >0%
Downloading file grossjava9hacks-1.3.3.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar failed :(
Global percentage >0%
Downloading file guava-25.1-jre.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar failed :(
Global percentage >0%
Downloading file trove-1.0.2.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/trove/trove/1.0.2/trove-1.0.2.jar failed :(
Global percentage >0%
Downloading file jansi-1.18.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/fusesource/jansi/jansi/1.18/jansi-1.18.jar failed :(
Global percentage >0%
Downloading file mcp_config-1.16.5-20210115.111550.zip with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip failed :(
Global percentage >0%
Downloading file eventbus-4.0.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar failed :(
Global percentage >0%
Downloading file json-simple-1.1.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar failed :(
Global percentage >0%
Downloading file accesstransformers-3.0.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar failed :(
Global percentage >0%
Downloading file jline-3.12.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar failed :(
Global percentage >0%
Downloading file forgespi-3.2.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar failed :(
Global percentage >0%
Downloading file log4j-iostreams-2.11.2.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/apache/logging/log4j/log4j-iostreams/2.11.2/log4j-iostreams-2.11.2.jar failed :(
Global percentage >0%
Downloading file commons-lang-2.6.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/commons-lang/commons-lang/2.6/commons-lang-2.6.jar failed :(
Global percentage >0%
Downloading file error_prone_annotations-2.1.3.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar failed :(
Global percentage >0%
Downloading file minecraft_server.1.16.5.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/minecraft_server.1.16.5.jar failed :(
Global percentage >0%
Downloading file animal-sniffer-annotations-1.14.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar failed :(
Global percentage >0%
Downloading file SpecialSource-1.8.5.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/md-5/SpecialSource/1.8.5/SpecialSource-1.8.5.jar failed :(
Global percentage >0%
Downloading file gson-2.8.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar failed :(
Global percentage >0%
Downloading file guava-20.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/guava/guava/20.0/guava-20.0.jar failed :(
Global percentage >0%
Downloading file terminalconsoleappender-1.2.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar failed :(
Global percentage >0%
Downloading file checker-qual-2.0.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0.jar failed :(
Global percentage >0%
Downloading file mixin-0.8.2.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar failed :(
Global percentage >0%
Downloading file maven-artifact-3.6.3.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar failed :(
Global percentage >0%
Downloading file sqlite-jdbc-3.34.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.jar failed :(
Global percentage >0%
Downloading file snakeyaml-1.27.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/yaml/snakeyaml/1.27/snakeyaml-1.27.jar failed :(
Global percentage >0%

**Mod list(模组列表) :** None

**Plugin list(插件列表) :** None

**Description of issue(描述) :** 在启动下载资源时下载失败

**Comment by Kotori0629** [comment]
http://nat.loliidc.cn:33644/job/LoliServer1.16/lastSuccessfulBuild/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-81-server.jar

**Comment by Kotori0629** [comment]
更新即可解决
