### ISSUE TITLE
[1.16] UUID string too large

### ISSUE THREAD

**Issue by ExSaltedFishPro** [Loli-Server/LoliServer1.16#184]
**Minecraft Version(我的世界版本) :** Minecraft version 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-81-server.jar"

**Operating System(操作系统) :** CentOS 7

**Concerned mod / plugin(有关的插件/Mod) :** AoA3

**Logs :https://paste.loliidc.cn/?41e86da8ef5af93b#Dw331FYZXMRqtFqicTVH3AFrzUiUxLMNs7b4nuUm8znk

**Steps to Reproduce(复现步骤) :**
 1. 安装模组
 2. 连接服务器
 3. Internal Server Error

**Description of issue :** UUID string too large 正版/离线登录都无法进入

**Comment by Kotori0629** [comment]
联系Aoa3开发组
