### ISSUE TITLE
[1.16] The problem with data packs. Received invalid biome id: -1

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#192]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-89-server.jar"

**Operating System(操作系统) :** Unbuntu 20

**Concerned mod / plugin(有关的插件/Mod) :** william-wythers-overhauled-overworld-for-1-16-5 DATA PACK
https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld-1-17-snapshots-edition//

**Logs :** https://paste.loliidc.cn/?ef7356d5ec1db187#HeztpTfkFQVWxhw9yGi7MJjU1CShQNgtzmnBB6NmMUWW

**Steps to Reproduce(复现步骤) :**
 1. If you visit 0 0 coordinates on the server after restart, the client will have numerous lags due to the -1 biome error
 2. Start server
 3. Stop server and add Data pack
 4. start server and tp 0 90 0
 5. restart server
 6. start moving along the biome, you will notice friezes, then check the client's logs! It can be around 140MB!
 7. 
**Description of issue :** Give all details about your issue

**Comment by Luohuayu** [comment]
Unable to reproduce
