### ISSUE TITLE
PlayerDeathEvent (not working)

### ISSUE THREAD

**Issue by GDVE** [Loli-Server/LoliServer1.16#193]
**Is your Suggestion related to a problem? Please describe.(建议是否与问题有关？请描述)**
PlayerDeathEvent - not working. He is handled but functions from event dont work.

**Additional context(附加)**
Inventory not keep and drops at ground
![image](https://user-images.githubusercontent.com/19783608/134696698-f6536a84-77b5-4579-aa87-97c6c235e809.png)

**Comment by XionioXMaster** [comment]
Agree

**Comment by GDVE** [comment]
Items do not drop upon death, but they are not saved by the player after event.setKeepInventory or same situation with event.setKeepLevel

**Comment by Kotori0629** [comment]
> Items do not drop upon death, but they are not saved by the player after event.setKeepInventory or same situation with event.setKeepLevel

可以使用中文详细说明吗？我没听懂你的意思。
Can I use the detailed description in Chinese?

**Comment by GDVE** [comment]
死亡时不再掉落物品。 但他们也没有得救。 这是有经验的。

**Comment by stanlystark** [comment]
will this be fixed?
