### ISSUE TITLE
[1.16] Large customer lagbacks due to custom Head

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#194]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-89-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** When Dungeons Arise - Forge!
https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise#c699

**Logs :** Nope

**Steps to Reproduce(复现步骤) :**
 1. I teleported here / locate dungeons_arise: giant_mushroom and found that the lags are created by the spawner of mobs
 2. as it turned out, the spawner spawns mobs with the heads of the players, the author believes that the heads create lags for the client, he suggested that I install the CustomSkinLoader mod, but he could not solve the problem, sometimes the custom heads installed in the world create 0/0 FPS for a few seconds for the players
 3. https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise#c699 In the comments below you can read the correspondence on this topic.

**Comment by Kotori0629** [comment]
It's not about loliserver, honey
