### ISSUE TITLE
[1.16] TAB plugin doesn't work

### ISSUE THREAD

**Issue by SSKirillSS** [Loli-Server/LoliServer1.16#195]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-90-server.jar

**Operating System(操作系统) :** Linux/Windows

**Concerned mod / plugin(有关的插件/Mod) :** **[TAB](https://www.mc-market.org/resources/20631/)** (You must be logged on to download)

**Logs :** https://pastebin.com/4zb06anE

**Steps to Reproduce(复现步骤) :**
 1. Drag-n-Drop plugin to your plugins folder
 2. Setup server and check console

**Description of issue :** Plugin just can't find remapped name of method in the `net.minecraft.server.v1_16_R3.ScoreboardTeam`

**Comment by Luohuayu** [comment]
Can't download
