### ISSUE TITLE
LoliServer-1.16.5-98-server.jar出现以下问题

### ISSUE THREAD

**Issue by Edwiinsgm** [Loli-Server/LoliServer1.16#201]
https://paste.loliidc.cn/?b87309eb6297876a#Cq2aVdwSNYBQN63B7qKpbueFcN1R63ok87h5dBou1rBD

**Comment by Kotori0629** [comment]
#202

**Comment by XionioXMaster** [comment]
[10:58:32][Server thread][INFO]: Generating keypair
=>....[10:58:32][Server thread][INFO]: Starting Minecraft server on *:25565
>....[10:58:32][Server thread][INFO]: Using epoll channel type
>....[10:58:32][Server thread][INFO]: This server is running LoliServer version 1.16.5-98 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.6)
>....[10:58:33][Server thread][INFO]: Debug logging is enabled
>....[10:58:33][Server thread][INFO]: Server Ping Player Sample Count: 12
>....[10:58:33][Server thread][INFO]: Using 4 threads for Netty based IO
>....[10:58:34][Server thread][INFO]: [CombatLogX] This plugin is using SirBlobmanAPI by SirBlobman.
>....[10:58:34][Server thread][INFO]: [CombatLogX] Searching for a handler that matches NMS version 1_16_R3
>....[10:58:34][Server thread][INFO]: [CombatLogX] Successfully found NMS Handler class 'com.SirBlobman.combatlogx.api.shaded.nms.NMS_1_16_R3'.
>....[10:58:35][Server thread][INFO]: [LuckPerms] Loading LuckPerms v5.3.67
>....[10:58:35][Server thread][INFO]: [PL-Hide] Loading PL-Hide v1.5.19
>....[10:58:35][Server thread][INFO]: [VillagerOptimiser] Loading VillagerOptimiser v1.1.5
>....[10:58:35][Server thread][INFO]: [IllegalStack] Loading IllegalStack v2.4.2
>....[10:58:35][Server thread][INFO]: [HolographicDisplays] Loading HolographicDisplays v2.4.9
>....[10:58:35][Server thread][INFO]: [Vault] Loading Vault v1.7.3-b131
>....[10:58:35][Server thread][INFO]: [F3Name] Loading F3Name v3.3.0
>....[10:58:35][Server thread][INFO]: [Chatty] Loading Chatty v2.19.4
>....[10:58:35][Server thread][INFO]: [WorldEdit] Loading WorldEdit v7.2.5+57d5ac9
>....[10:58:38][Server thread][INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@4f6c22ac]
>....[10:58:38][Server thread][INFO]: [EntityTrackerFixer] Loading EntityTrackerFixer v1.3.3
>....[10:58:38][Server thread][INFO]: [ChatBubbles] Loading ChatBubbles v1.17.1.a.1
>....[10:58:38][Server thread][INFO]: [WorldGuard] Loading WorldGuard v7.0.4+2073-014277f
>....[10:58:38][Server thread][INFO]: [DangerousCaves] Loading DangerousCaves v2.2.13;24
>....[10:58:39][Server thread][INFO]: [WGExtender] Loading WGExtender v3.0
>....[10:58:39][Server thread][INFO]: [CombatLogX] Loading CombatLogX v10.3.8.1
>....[10:58:39][Server thread][INFO]: [CombatLogX] Loading expansions...
>....[10:58:39][Server thread][INFO]: [CombatLogX] Successfully loaded 11 expansions.
>....[10:58:39][Server thread][INFO]: [CombatLogX] Судьба загрузилась успешно.
>....[10:58:39][Server thread][INFO]: [TabList] Loading TabList v5.5.6
>....[10:58:39][Server thread][INFO]: [CMILib] Loading CMILib v1.0.3.11
>....[10:58:39][Server thread][INFO]: [CMI] Loading CMI v9.0.2.9
>....[10:58:39][Server thread][INFO]: [LuckPerms] Enabling LuckPerms v5.3.67
>....[10:58:41][Server thread][INFO]: __
>....[10:58:41][Server thread][INFO]: | |__) LuckPerms v5.3.67
>....[10:58:41][Server thread][INFO]:

**Comment by Kotori0629** [comment]
Try , move files to folder
