### ISSUE TITLE
[1.16] GriefDefender插件问题 添加kyori-adapter

### ISSUE THREAD

**Issue by Woundwortlili** [Loli-Server/LoliServer1.16#205]
Minecraft Version(我的世界版本) : 1.16.5 Minecraft version

LoliServer buildVersion(构建版本) : LoliServer-1.16.5-103-server.jar

Operating System(操作系统) : Windows Server 2019

Concerned mod / plugin(有关的插件/Mod) :
GriefDefender https://www.spigotmc.org/resources/1-12-2-1-17-1-griefdefender-claim-plugin-grief-prevention-protection.68900/
[前置插件]LuckPerms https://www.spigotmc.org/resources/luckperms.28140/

Logs : 无任何报错

Steps to Reproduce(复现步骤) :
 1. 下载并安装插件
 2. 在聊天栏输入griefdefender的指令
 3. 聊天栏显示的信息无法进行点击且无悬浮信息

Description of issue : 输入griefdefender的指令后聊天栏会显示信息,点击聊天栏内的信息无法执行操作并且无悬浮显示

**Comment by Kotori0629** [comment]
![HV_DWU$UP)~0U Y2J9SE)OF](https://user-images.githubusercontent.com/81866089/135868179-635909ee-d576-4b9b-82cf-8dbc385b6974.png)
![image](https://user-images.githubusercontent.com/81866089/135868242-c8e9387c-9d9e-4a81-9c41-5c637c6aec39.png)
