### ISSUE TITLE
[1.16] Survive mod crash

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#208]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-110-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** https://www.curseforge.com/minecraft/mc-mods/survive/files/3416821
https://www.curseforge.com/minecraft/mc-mods/create **more mods in the log, but the problem is between create and survive. mixin?**

**Logs :** https://paste.loliidc.cn/?6d2de8991150d6b9#DHMQyMJ29xGMRcbAkKvXGDYxVbosHmAY1Rnrt9VXpFF4

**Steps to Reproduce(复现步骤) :**
 1. Just install these 2 mods and start the server, everything works correctly on the client

**Description of issue :** Give all details about your issue

**Comment by Kotori0629** [comment]
Please upload the report again and select never expire
