### ISSUE TITLE
[1.16] FartherViewDistance Plugin - Doesn't work as it should

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#221]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-108-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** FartherViewDistance, CMI, CMILib Plugin

**Logs :** https://paste.loliidc.cn/?72caee5e26966c82#DD56Na7ocrPwR4Upzj3gcfaiLoYWG6vBUzRRzSG2jhxY

**Steps to Reproduce(复现步骤) :**
 1. Download version 6.1.6
 2.  Download ProtocolLib
 3. - Spigot server, config.yml server-tick-max-generate-amount to 0

**Description of issue :** The plugin should display the already loaded fragments, but instead it does not load anything.

**Comment by Kotori0629** [comment]
This may be a plugin code logic problem
