### ISSUE TITLE
[1.16] Dupe ability via mod side

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#241]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-160-server.jar"

**Operating System(操作系统) :** iunbuntu 20

**Concerned mod / plugin(有关的插件/Mod) :** Quark mod, Ishops Plugin 1.16 version

**Logs :** Nope 
There are no errors related to this.

**Steps to Reproduce(复现步骤) :**
 1. Let's install the Quark mod and the Ishops plugin - or another GUI plugin
 2. start the server, enter it and create a store or open the GUI
 Click on Extract with the plugin GUI open
 3. ![image](https://user-images.githubusercontent.com/86433158/138411960-22ca6704-eb6c-423b-a2f4-35490724e4da.png)
 
![image](https://user-images.githubusercontent.com/86433158/138412041-1791aa48-3c42-4402-8fa9-8f880f5b9f84.png)

**Description of issue :** Now all the things that are available in the Spigot-GUI plugins can be pulled out using mods for auxiliary actions

**Comment by Kotori0629** [comment]
Don't you think it's a problem with the box sorting module？
