### ISSUE TITLE
[1.16] ACubulets hologram displaying (probably a ProtocolLib issue)

### ISSUE THREAD

**Issue by SSKirillSS** [Loli-Server/LoliServer1.16#245]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-160-server

**Concerned mod / plugin(有关的插件/Mod) :** ACubelets, ProtocolLib, HolographicDisplays

**Steps to Reproduce(复现步骤) :**
 1. Install all 3 mentioned plugins
 2. Create `nether.yml` file with this text (https://pastebin.com/2cLuFU5L) in your `plugins/ACubelets/types` folder
 3. Start the server, find somewhere other player, place End Portal Frame, look at it and use `/cubelets machine create` command
 4. Use `cubelets give YOUR_NICKNAME nether 5` command and looks at your created cubelets machine

**Description of issue :** Some description strings will overlap other strings because it will show holograms for player who have cubelets to open, and who don't have at the same time.

**Comment by Kotori0629** [comment]
Hard to fix
