### ISSUE TITLE
[1.16] botania (i think) crashing server upon a player joining

### ISSUE THREAD

**Issue by Xplodin** [Loli-Server/LoliServer1.16#246]
**Minecraft Version(我的世界版本) :** {1.16.5 version}

**LoliServer buildVersion(构建版本) :** {160}

**Operating System(操作系统) :** {Ubuntu 18.04}

**Logs :** {Link(s) of logs and crash reports if you have}, (https://paste.loliidc.cn)
https://paste.loliidc.cn/?431f0c4db86e1af6#3bHmVk9chqj5Cn1LqKvhvDtrp2A12NdhatRCrT5NPAsh
**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
FTB OceanBlock 1.4.1
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
LuckPerms PlayerLands ClearLag w timer Elitelootbox CMI Ultimate auto restart Votifier Vault Superbvote
**Description of issue(描述) :** {Give all details about your issue}
As soon as a player enters, the server crashes

**Comment by XionioXMaster** [comment]
Your log is empty, period expired

**Comment by Kotori0629** [comment]
Log expired

**Comment by Xplodin** [comment]
I'll grab a new one when I get home. If the issue exists still

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 3, 2021 at 3:15 PM, ***@***.***> wrote:   


Log expired

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
