### ISSUE TITLE
[1.16] Loli bug hopper crash

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#247]
**Minecraft Version(我的世界版本) :** 1 16 5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-160-server.jar"

**Operating System(操作系统) :** win10

**Concerned mod / plugin(有关的插件/Mod) :** GreekFantasy 

**Logs :** https://paste.loliidc.cn/?85dfcbeaf6359008#5TRzyCmmME4WiAzFGzxkBnREJ8vPUvUZcmmFUNHm1bda

**Steps to Reproduce(复现步骤) :**
 1. I don’t know what caused it

**Comment by XionioXMaster** [comment]
in this case, as I found out, after installing any chest from the Quark mod under the bunker, we put an item from the GreekFantasy mod into the chest and we get a server crash

But I believe that an item from any other mod will work as well.

**Comment by DonorKrovi** [comment]
> It is recommended not to submit issues if you don't know how to reproduce them in the future

Hello I have the same problem. If you put something out of fashion in a mod chest under bunker, we get a server crash!

**Comment by Kotori0629** [comment]
So, how to reproduce?

**Comment by ahdg6** [comment]
和 QUARK 的箱子有关，只需要用漏斗漏 QUARK MOD 新加的箱子就会炸了

**Comment by Kotori0629** [comment]
> 和 QUARK 的箱子有关，只需要用漏斗漏 QUARK MOD 新加的箱子就会炸了

没有复现

**Comment by Kotori0629** [comment]
我并没有在LoliServer重现这个问题..

**Comment by XionioXMaster** [comment]
> 我并没有在LoliServer重现这个问题..

很奇怪，你用的是夸克箱子还是香草箱子？这很重要。

**Comment by XionioXMaster** [comment]
> 我并没有在LoliServer重现这个问题..

奇怪，你用的是“夸克”宝箱还是香草宝箱？这是非常重要的。

**Comment by Kotori0629** [comment]
> > 我并没有在LoliServer重现这个问题..
> 
> 奇怪，你用的是“夸克”宝箱还是香草宝箱？这是非常重要的。

香草
