### ISSUE TITLE
How can I determine the exact cause of a server crash?

### ISSUE THREAD

**Issue by DonorKrovi** [Loli-Server/LoliServer1.16#249]
**Is your Suggestion related to a problem? Please describe.(建议是否与问题有关？请描述)**
I have many cases of server crashes, this is not a crash-report and I do not understand what the problem might be, what methods can you offer me to find the reason

judging by the magazine I sent you below is it because of luckyperms? or I'm wrong?
https://paste.loliidc.cn/?091d97f138c7805b#H2ZgkxtMNCNET1oyk4i8gFKuUfWxge6CaRD1BUECWDt3

**Comment by Kotori0629** [comment]
No, thread locked. try to restart server.
