### ISSUE TITLE
[1.16] Dregora mod - crash server

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#250]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-160-server.jar"

**Operating System(操作系统) :** Win 10

**Concerned mod / plugin(有关的插件/Mod) :** Dregora mod https://www.curseforge.com/minecraft/mc-mods/dregora + 
[OpenTerrainGenerator-1.16.5-0.0.19.zip](https://github.com/Loli-Server/LoliServer1.16/files/7459203/OpenTerrainGenerator-1.16.5-0.0.19.zip)

**Logs :** https://paste.loliidc.cn/?3070db76e21be7a9#AYUPahDqPYVVfmCfYhqZeQRjVDLoy1bfqhQbQ5a4iq7y

**Steps to Reproduce(复现步骤) :**
 1. Launch server
 2.Done

**Comment by Kotori0629** [comment]
Today fix

**Comment by XionioXMaster** [comment]
> Today fix

i love you!

**Comment by XionioXMaster** [comment]
> Today fix

When will this method be added?

**Comment by Kotori0629** [comment]
Don't fix
