### ISSUE TITLE
[1.16] Crash with Supplementaries projectiles

### ISSUE THREAD

**Issue by SSKirillSS** [Loli-Server/LoliServer1.16#251]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-160-server

**Concerned mod / plugin(有关的插件/Mod) :** supplementaries-1.16.5-0.17.7

**Logs :** https://pastebin.com/e0hW7Mzc

**Steps to Reproduce(复现步骤) :**
 1. Take slingshot and any block to your inventory
 2. Use slingshot to shoot this block

**Description of issue :** This crash is rly weird and can be reproduced with any projectile from this mod. Sometimes when spawning projectiles, server will be crashed. Chance close to 1%, but when you have 5+ players on your server, this thing will be rly annoying.

**Comment by Kotori0629** [comment]
#167 duplicated, report to mod author
