### ISSUE TITLE
[BUG 1.16.5] Quark BackPack dupe resources

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#255]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 160

**Operating System(操作系统) :** Windows 10, 64 bit

**Logs :** no logs

**Mod list(模组列表) :** Quark

**Plugin list(插件列表) :** no plugins

**Description of issue(描述) :** when I put on my backpack and open the inventory, drag items in the inventory into the crafting slot, then they disappear or multiply, please fix it!

**Comment by XionioXMaster** [comment]
https://github.com/Loli-Server/LoliServer1.16/issues/138

**Comment by MrJorman** [comment]
no fixed

**Comment by XionioXMaster** [comment]
> no fixed

Fixi sam, eto na storone moda

**Comment by Kotori0629** [comment]
Give me video . I don't know how to repeat.
