### ISSUE TITLE
[BUG 1.16.5] the border of the world flies off after a server reboot

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#256]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 160

**Operating System(操作系统) :** Windows 10, 64 bit

**Logs :** no logs

**Mod list(模组列表) :** This bug works without mods

**Plugin list(插件列表) :** This bug works without plugins

**Description of issue(描述) :** When I write /worldborder set (number) in the normal world, the border is created in all worlds, but after a reboot, the world border flies to world_nether, world_the_end and I have to re-register the world border after each reboot.

**Comment by XionioXMaster** [comment]
Please provide a complete list of plugins and mods, I cannot reproduce this on a clean version of Loli

**Comment by MrJorman** [comment]
This bug works without plugins. We write in the normal world / worldborder set 10, teleport to world_nether, after which we see the same world border there, if it is not there, we write / worldborder set 10, after which we restart the server - we go and there are no borders in world_nether and world_the_end again

**Comment by Kotori0629** [comment]
> Please provide a complete list of plugins and mods, I cannot reproduce this on a clean version of Loli

Can you repeat it ?

**Comment by MrJorman** [comment]
> > Please provide a complete list of plugins and mods, I cannot reproduce this on a clean version of Loli
> 
> Can you repeat it ?

yes

**Comment by Kotori0629** [comment]
> > > Please provide a complete list of plugins and mods, I cannot reproduce this on a clean version of Loli
> > 
> > 
> > Can you repeat it ?
> 
> yes

Give me video

**Comment by MrJorman** [comment]
fix bug pls, no video. 
When I write /worldborder set (number) in the normal world, the border is created in all worlds, but after a reboot, the world border flies to world_nether, world_the_end and I have to re-register the world border after each reboot.

**Comment by Kotori0629** [comment]
No repeat
