### ISSUE TITLE
Please tell me what module caused the crash

### ISSUE THREAD

**Issue by QianMuu** [Loli-Server/LoliServer1.16#257]
描述：服务器tick循环异常
java.lang.ArrayIndexOutOfBoundsException: -1
 	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.fixPointers(LongLinkedOpenHashSet.java:735) ~[? :?] {re:classloading}
 	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.shiftKeys(LongLinkedOpenHashSet.java:398) ~[?:?] {re:classloading}
 	at it.unimi.dsi.fastutil.longs .LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:484) ~[?:?] {re:classloading}
	在 net.minecraft.world.lighting.LevelBasedGraph.func_215483_b(LevelBasedGraph.java:194) ~[?:?] {re: classloading}
	在 net.minecraft.world.server.TicketManager$PlayerChunkTracker.func_215497_a(TicketManager.java:423) ~[?:?] {re:classloading}

	在 net.minecraft.world.server.TicketManager$PlayerTicketTracker.func_215497_a(TicketManager.java:482) ~[?:?] {re:classloading}
	在 net.minecraft.world.server.TicketManager.func_219353_a(TicketManager.java:96 ) ~[?:?] {re:classloading}
	在 net.minecraft.world.server.ServerChunkProvider.func_217235_l(ServerChunkProvider.java:304) ~[?:?] {re:mixin,pl:accesstransformer:B,pl: runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	在 net.minecraft.world.server.ServerChunkProvider.access$200(ServerChunkProvider.java:49) ~[?:?] {re:mixin ,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	在 net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:581) ~[?:?] {re:classloading}
	在 net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:300 ) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	在 net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:856) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B, pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP: byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	在 net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:845) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B, pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP: byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	在 net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119) ~[?:?] {re: mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	在 net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:831) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B, pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP: byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	在 net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:763) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B, pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP: byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	在 net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B, pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP: byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	在 java.lang.Thread.run(Unknown Source) [?:1.8.0_201] {}

**Comment by Kotori0629** [comment]
重启一手会好
