### ISSUE TITLE
[1.16] Plugin - DeluxeTags BUG

### ISSUE THREAD

**Issue by binglingyao** [Loli-Server/LoliServer1.16#259]
**Minecraft Version(我的世界版本) :** Minecraft version
1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-******-server.jar"
172
**Operating System(操作系统) :** Provide the name of your OS
windows
**Concerned mod / plugin(有关的插件/Mod) :** Provide mod / plugin name and download link if possible
- DeluxeTags
**Logs :** Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)
https://paste.loliidc.cn/?6a771c25a16680d3#KyjcyX7xFMn6hSrayDBznikj5a2itmDUQ5p3Ma1kCiv
**Steps to Reproduce(复现步骤) :**
 1. Do it
 2. Then do that
 3. ...
- 1.安装DeluxeTags
- 2.客户端输入/tags
- 3.报错
**Description of issue :** Give all details about your issue

**Comment by XionioXMaster** [comment]
**LoliServer-1.16.5-******-server.jar ?

Do it
Then do that**
... ??????????????????

**Comment by binglingyao** [comment]
LoliServer-1.16.5-172-server.jar 

1.install DeluxeTags.jar  (this is plugin)
2.use client typing: /tags
3.server server reported an error.

Sorry, I wrote it below. The original text is in Chinese, so I may not understand it, so I wrote it here to supplement

**Comment by binglingyao** [comment]
Add-on: DeluxeTags related plug-in dependencies have been installed

**Comment by Kotori0629** [comment]
Log expiration
