### ISSUE TITLE
[1.16] Connectivity Incompatability

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Loli-Server/LoliServer1.16#260]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : Provide LoliServer buildVersion: 170 

Operating System(操作系统): Ubuntu 18.04

Concerned mod / plugin(有关的插件/Mod) : https://www.curseforge.com/minecraft/mc-mods/connectivity

Logs: https://paste.vcnet.work/heyadigopo.md

Steps to Reproduce(复现步骤) :

Install this modpack: https://transfer.sh/kdnyJ9/ABOE%201.16.5%20Testing-2.3.4.zip
Try join a compatible LoliServer,
Error message on join.

Description of issue: 
When using connectivity it is supposed to resolve login timeouts and fix multiple issues due to login issues and large packets being sent all at once, works fine in forge and is actually the only way to login with forge, without this mod its impossible to log in with forge or loli due to large packet sizes.

From what I can gather it looks like whatever is being done to overwrite networking and login packets for LoliServer isn't taking into consideration changes from Connectivity which is inherently fixing Minecraft & Forge, The best solution I can see here is by combining both LoliServer and the changes made in Connectivity thus removing the requirement for this on the servers end resolving the issue.

**Comment by Kotori0629** [comment]
建议不要使用这样的模组, 他可能并不能在CraftBukkit-nmsPatch修改后正常工作

**Comment by SirOMGitsYOU** [comment]
> It is recommended not to use such a module, it may not work properly after CraftBukkit-nmsPatch is modified

Without this module forge with this pack is impossible due to the main vanilla coding, could this patch potentially be impleted into core Loli?

**Comment by Kotori0629** [comment]
I installed this mod and entered the server, but there was no error

**Comment by SirOMGitsYOU** [comment]
> I installed this mod and entered the server, but there was no error

Yes because the mod doesn’t do anything with a small amount of mods or medium it has to have enough mods to where it’s required to alter the vanilla packet sizes because the craft bukkit patches are overriding the vanilla patches this makes it unusable for kitchen sink esque modpacks
