### ISSUE TITLE
[1.16.5] BUG WITH MOD SEEKER COMPASS

### ISSUE THREAD

**Issue by Pqvel1l** [Loli-Server/LoliServer1.16#261]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : 160

Operating System(操作系统) : Windows 10, 64 bit

Logs : https://pastebin.com/bJvjnJ4h

Mod list(模组列表) : Seeker compass

Plugin list(插件列表) : no plugins

**Steps to Reproduce(复现步骤) :**
 1. Enchant Seeker Compass to Summoning
 2. Bind to Entity
 3. Try to summon the entity using the seeker's compass

**Description of issue :** Give all details about your issue

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/142762931-2be838ae-58f7-45e9-89fd-8f917761e634.png)
Contact to mod author, this bug repeat on forge-36.2.8-server
