### ISSUE TITLE
[1.16.5] BUG WITH WorldGuard 7.0.4

### ISSUE THREAD

**Issue by Pqvel1l** [Loli-Server/LoliServer1.16#262]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : 160

Operating System(操作系统) : Windows 10, 64 bit

Logs : No logs

Mod list(模组列表) : no mods

Plugin list(插件列表) : World Guard 7.0.4

**Steps to Reproduce(复现步骤) :**
1. Claim Region
2. Put any block that has a two-block structure (beds,doors)
3. It turns out a dupe of beds and doors.

**Description of issue :** 
A player who is not registered in another player's region can put a bed or a door and it will remain, as well as a dupe.

This was not observed on the Moist core

**Comment by Kotori0629** [comment]
Can you give me video? i don't know your mean

**Comment by Pqvel1l** [comment]
> Can you give me video? i don't know your mean

No, I can't send the video because my internet is very bad.

**Comment by XionioXMaster** [comment]
> > Can you give me video? i don't know your mean
> 
> No, I can't send the video because my internet is very bad.

Напиши по русски
