### ISSUE TITLE
[1.16.5] ice and fire/冰火传说 2.1.8/2.1.9 生成龙巢时卡顿 服务端版本#172

### ISSUE THREAD

**Issue by HerbertBin** [Loli-Server/LoliServer1.16#263]
Minecraft version：1.16.5

LoliServer  buildVersion: "LoliServer-1.16.5-172-server.jar"、"LoliServer-1.16.5-160-server.jar"

Operating System: Windows 10 20H2

Concerned mod / plugin(有关的插件/Mod) : ice and fire/冰火传说 2.1.8/2.1.9

服务端错误提示：
[Server] [00:01:57][Server thread][WARN]: Tried to load a block entity for block Block{minecraft:cave_air} but failed at location BlockPos{x=11560, y=23, z=11885}
[Server] [00:01:57][Server thread][WARN]: Tried to load a DUMMY block entity @ BlockPos{x=11561, y=14, z=11874} but found not block entity block Block{minecraft:coal_ore} at location
[Server] [00:01:57][Server thread][WARN]: Tried to load a block entity for block Block{minecraft:coal_ore} but failed at location BlockPos{x=11561, y=14, z=11874}
[Server] [00:01:57][Server thread][WARN]: Tried to load a DUMMY block entity @ BlockPos{x=11558, y=14, z=11877} but found not block entity block Block{minecraft:diorite} at location
[Server] [00:01:57][Server thread][WARN]: Tried to load a block entity for block Block{minecraft:diorite} but failed at location BlockPos{x=11558, y=14, z=11877}
......

Steps to Reproduce(复现步骤) :
找到未生成过的龙巢；
以及部分未生成过模组新增结构会报错（似乎主体结构生成位置为空气就不会出现错误）

Description of issue :
提示错误的坐标本该是龙巢的一部分，但是实际都是原版的方块，且位于区块交界处

**Comment by XionioXMaster** [comment]
As far as I remember, this error is from version 1.12.2, and there is even a pure Forge
