### ISSUE TITLE
[1.16] mcrmb插件无法打开游戏内支付二维吗

### ISSUE THREAD

**Issue by DE-SHARK** [Loli-Server/LoliServer1.16#264]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : LoliServer-1.16.5-172-server.jar

Operating System(操作系统) : Windows 10

Concerned mod / plugin(有关的插件/Mod) : MCRMB-2.0b19-12fe19a.jar

Logs : https://paste.loliidc.cn/?9b7eddb0b316a16e#3bHE1utftq6Jvu9iT7vK6a1DHECMJVMtt6NCU8er8aHE

Steps to Reproduce(复现步骤) :
 1. 按照wiki安装及配置好mcrmb插件
 2. 游戏内输入指令：/b wx 1
 3. 报错
![(YN$Y}FU 4H1}T29$Z8%$81](https://user-images.githubusercontent.com/64623974/141609379-b28e2681-2304-4856-ab3a-ae315e3e7c81.png)

**Comment by Kotori0629** [comment]
在Spigot或Craftbukkit是否能复现这个问题？

**Comment by DE-SHARK** [comment]
> 在Spigot或Craftbukkit是否能复现这个问题？

在spigot端上，插件列表相同的情况下，无法复现这个问题
