### ISSUE TITLE
[1.16] Far From Home 7 crash

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#266]
**Minecraft Version(我的世界版本) :** Minecraft version 1 16

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-172-server.jar"

**Operating System(操作系统) :** win 10

**Concerned mod / plugin(有关的插件/Mod) :** [Provide mod / plugin name and download link if possible]

(https://www.curseforge.com/minecraft/mc-mods/far-from-home)
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go
https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator

**Logs :** https://paste.loliidc.cn/?cf3ae61e6bd5939d#AxXxuSkwDwWSHxUxVcmap45gsNY8FWyQ9VtGpc4HA11k

**Steps to Reproduce(复现步骤) :**
 To Use On a Server

Set level-name to "Far From Home 7" or "Far From Home 6"

Set level-type to "OTG"

Run server = crash

**Description of issue :** A similar error occurs here too. https://github.com/Loli-Server/LoliServer1.16/issues/250

**Comment by Kotori0629** [comment]
Duplicated #250
