### ISSUE TITLE
Server latency when connecting a new player

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#269]
**Minecraft Version(我的世界版本) :**  1 16

**LoliServer buildVersion(构建版本) :** 172

**Operating System(操作系统) :** Unbuntu 20

**Logs :** There are no errors in the console, standard startup

**Mod list(模组列表) :** Atum 2, Quark, BetterEnd, BetterNether

**Plugin list(插件列表) :** CMI, CMIlib, Chatty, ProtocolLib, TabList, LuckyPerms, WorldGuard, WorldEdit

**Description of issue(描述) :** When player 2 connects to the server, the server does not work for about 5-6 seconds, after which he dies and some TPS drawdowns are visible. Online mode is enabled on my server! unfortunately, I cannot provide you with the log due to the fact that my hosting lease has expired and on my computer I cannot reproduce it due to
for a small amount of RAM. During the connection of 2 players, all living creatures freeze, and if you break the block above which the grass is located, it will remain in the air.

try to reproduce this on a clean server

**Comment by Kotori0629** [comment]
It's not a problem with loliserver
