### ISSUE TITLE
[BUG 1.16.5] Quark BackPack dupe resources

### ISSUE THREAD

**Issue by TheKlimoT** [Loli-Server/LoliServer1.16#280]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : 185

Operating System(操作系统) : Debian 10
Logs : no logs

Mod list(模组列表) : Quark

Plugin list(插件列表) : no plugins

Description of issue(描述) : when I put on my backpack and open the inventory, drag items in the inventory into the crafting slot, then they disappear or multiply, please fix it!

VIDEO: https://www.youtube.com/watch?v=JYtJ4uC0Amg

**Comment by TheKlimoT** [comment]
Error: https://www.toptal.com/developers/hastebin/kozimogewa.md

**Comment by Kotori0629** [comment]
Thank you for your feedback. This seems to be a bad question. Please wait for me to test

**Comment by Kotori0629** [comment]
And, can you use https://paste.loliidc.cn/ ?

**Comment by TheKlimoT** [comment]
https://paste.loliidc.cn/?f43dde390bfd0f69#4or9Z6HxpRMBKk8EU9aMKbvfgPqjJmPRfZJ5iwcziqDt
