### ISSUE TITLE
[1.16] Plugin system

### ISSUE THREAD

**Issue by joaoespanhol** [Loli-Server/LoliServer1.16#282]
**Minecraft Version(我的世界版本) :** Minecraft version: 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "This server is running LoliServer version 1.16.5-185 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.19)"

**Operating System(操作系统) :** Provide the name of your OS: windows 11

**Concerned mod / plugin(有关的插件/Mod) :** System - link: https://gamersboard.com.br/topic/61255-system-o-seu-novo-super-essentials/

**Logs :** Link(s) of logs and crash reports if you have: https://pastebin.com/22eMg4ys / https://pastebin.com/Jb5XfXXB

**Steps to Reproduce(复现步骤) :**
 1. start server
 2. enter server
 3. ...

**Description of issue :** Give all details about your issue

**Comment by Kotori0629** [comment]
I think..... duplicated of #238
