### ISSUE TITLE
[1.16] SPAM ERROS CONSOLE

### ISSUE THREAD

**Issue by joaoespanhol** [Loli-Server/LoliServer1.16#283]
**Minecraft Version(我的世界版本) :** Minecraft version: 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "This server is running LoliServer version 1.16.5-185 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.19)"

**Operating System(操作系统) :** Provide the name of your OS: windows 11

**Concerned mod / plugin(有关的插件/Mod) :** System - link: https://gamersboard.com.br/topic/61255-system-o-seu-novo-super-essentials/ and QUICKSHOP: https://www.spigotmc.org/resources/quickshop-reremake-1-17-ready-multi-currency.62575/

**Logs :** Link(s) of logs and crash reports if you have: https://mclo.gs/EYkYXKj

**Steps to Reproduce(复现步骤) :**
 1. start server
 2. enter server
 3. ...

**Description of issue :** SPAM CONSOLE FOR ERROS:

Could not pass event PlayerDeathEvent to System v1.14.18
Error encoding packet
Could not pass event InventoryCloseEvent to QuickShop v5.0.0.14

**Comment by Kotori0629** [comment]
Try contact author

**Comment by joaoespanhol** [comment]
no have this problem magma and mohist
