### ISSUE TITLE
Remove spam info mod: randompatches

### ISSUE THREAD

**Issue by joaoespanhol** [Loli-Server/LoliServer1.16#284]
**Is your Suggestion related to a problem? Please describe.(建议是否与问题有关？请描述)**
The server constantly gets a random Path to give SPAM, so it is difficult to read directly from a console as other information and error.
Not to mention that the logs are huge.

**Describe the solution you'd like(描述你想要的解决方案)**
capture this information and do not log or console display.

**Additional context(附加)**
Log: https://mclo.gs/EYkYXKj

**Comment by Kotori0629** [comment]
Try use https://www.spigotmc.org/resources/console-spam-fix.18410/history
