### ISSUE TITLE
[1.16] crasher digital miner mekanism

### ISSUE THREAD

**Issue by joaoespanhol** [Loli-Server/LoliServer1.16#285]
**Minecraft Version(我的世界版本) :** Minecraft version: 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "This server is running LoliServer version 1.16.5-185 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.19)"

**Operating System(操作系统) :** Provide the name of your OS: windows 11

**Concerned mod / plugin(有关的插件/Mod) :** mekanism

**Logs :** Link(s) of logs and crash reports if you have: https://mclo.gs/QPIenBJ

**Steps to Reproduce(复现步骤) :**
 1. start server
 2. enter server
 3. ...

**Description of issue :**

**Comment by Kotori0629** [comment]
Contact to mod author.

**Comment by joaoespanhol** [comment]
no have this problem magma and mohist
