### ISSUE TITLE
[1.16] The EliteMobs cannot be used normally

### ISSUE THREAD

**Issue by ConstanceJess** [Loli-Server/LoliServer1.16#288]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-185-server.jar"

**Operating System(操作系统) :** windows10

**Concerned mod / plugin(有关的插件/Mod) :** EliteMobs

**Logs :** https://paste.loliidc.cn/?079cbf97d64a628d#FTes1VPgsia8pgAFuy5FuNt2zJ5ewk16R5FCLSTjSWvE

**Steps to Reproduce(复现步骤) :**
 1. 输入em shop
 2. 点击购买商店
 3. 控制台提示报错
 4. 输入em打开菜单也是错乱

**Description of issue :** 
插件地址
①**spigot** https://www.spigotmc.org/resources/%E2%9A%94elitemobs%E2%9A%94.40090/
②**mcbbs** https://www.mcbbs.net/thread-822085-1-1.html

**Comment by KomiMoe** [comment]
无法复现。请上传你的所有mod列表后重新打开issue

**Comment by ConstanceJess** [comment]
您好	官方已经收到了您的邮件。我们正在调查您的反馈，并会尽快给您答复。这是一封自动发送的电子邮件。如果您回复此邮件，将无人阅读。请使用上面的链接更新您的请求。我们将通过电子邮件回复您的请求。云楼阁管理组https://www.yunlouge.cn/
