### ISSUE TITLE
[1.16] Denizen | ImpossibleTrigger | ClassNotFoundException

### ISSUE THREAD

**Issue by Tomut0** [Loli-Server/LoliServer1.16#289]
Minecraft Version(我的世界版本) : **1.16.5**

LoliServer buildVersion(构建版本) : **185**

Operating System(操作系统) : **Oracle Linux Server 7.9 aarch64**

Concerned mod / plugin(有关的插件/Mod) : [Denizen](https://ci.citizensnpcs.co/job/Denizen/1755/)

Logs : [paste.loliidc.cn](https://paste.loliidc.cn/?23481941b4b19df6#EDqsQ1eN4fotUbdG514mSyWbo2gpQuVEmLGEPRmdBbuD)

**Steps to Reproduce(复现步骤) :**
 1. Install the latest Denizen build from Jenkins
 2. Run the server

**Comment by Kotori0629** [comment]
Use paste.loliidc.cn

**Comment by Tomut0** [comment]
> Use paste.loliidc.cn

Updated.
I have a slow connection to Chinese web-sites. ☕

**Comment by Kotori0629** [comment]
> > Use paste.loliidc.cn
> 
> Updated. I have a slow connection to Chinese web-sites. ☕

I think you can try citizens, which may not be supported

**Comment by Tomut0** [comment]
> I think you can try citizens, which may not be supported
Citizens and denizen are linked each other.
Denizen provides a more comfortable way to write something like "plugins".
(In my opinion, it's better to write a small script file than to create another one plugin)

I'm not familiar with writing server cores (that's why I reported), but I can  definitely tell that the problem is find the class.
In Forge I have found `ImpossibleTrigger`, not `ImpossibleTrigger$a`.

I decided that the problem could be in mappings, then I tried another Denizen versions, like: 1752, 1724 and the latest one.
But the problem remained. In another server core there wasn't that error. 👀 

![изображение](https://user-images.githubusercontent.com/42711312/144879176-8df009b0-cd75-4482-b91d-98fcab552e23.png)

**Comment by Kotori0629** [comment]
> > I think you can try citizens, which may not be supported
> > Citizens and denizen are linked each other.
> > Denizen provides a more comfortable way to write something like "plugins".
> > (In my opinion, it's better to write a small script file than to create another one plugin)
> 
> I'm not familiar with writing server cores (that's why I reported), but I can definitely tell that the problem is find the class. In Forge I have found `ImpossibleTrigger`, not `ImpossibleTrigger$a`.
> 
> I decided that the problem could be in mappings, then I tried another Denizen versions, like: 1752, 1724 and the latest one. But the problem remained. In another server core there wasn't that error. 👀
> 
> ![изображение](https://user-images.githubusercontent.com/42711312/144879176-8df009b0-cd75-4482-b91d-98fcab552e23.png)

Okay
