### ISSUE TITLE
LoliServer error with FastWorkbench

### ISSUE THREAD

**Issue by AlkaDg** [Loli-Server/LoliServer1.16#290]
Hello, I started a LoliServer in 1.16.5, and when starting any modpacks containing FastWorkbench Mod, the server won't start, it seems like it is a Workbench problem, have you got any advices on how I can fix this ? Because when I start the server with juste forge + minecraft server, it works fine.

Here is the pastebin for the logs when FastWorkbench is in the mods file : http://pastebin.fr/98808
Here is the pastebin for the logs when FastWorkbench isn't in the mods file : http://pastebin.fr/98809

The server is a Debian 10 machine in x64 with 18 GB RAM, running under Java 11, a 6vCore CPU and a 160Go SSD.

**Comment by Kotori0629** [comment]
#302
