### ISSUE TITLE
[1.16] tick崩溃

### ISSUE THREAD

**Issue by 3269199948** [Loli-Server/LoliServer1.16#292]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-185*-server.jar"

**Operating System(操作系统) :** Win11

**Concerned mod / plugin(有关的插件/Mod) :** 我自己写的，没发出来

**Logs :** Link(s) https://paste.ubuntu.com/p/2w2PTfrsBy/

**Steps to Reproduce(复现步骤) :**

**Description of issue :** Give all details about your issue

com.ocean.chinacraft就是我的包名
onArmorTick全部代码：https://paste.ubuntu.com/p/phRRqgsbJD/

我在单人测试完全没有问题

Forge版本：1.16.5-36.2.2

第59行，就是  if (player.isAlive() && Screen.hasShiftDown())

**Comment by Kotori0629** [comment]
在Forge服务端尝试过吗

**Comment by 3269199948** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 3269199948** [comment]
> 在Forge服务端尝试过吗

试了一下，好像也会这样，奇怪了，为啥呢

**Comment by Kotori0629** [comment]
> > 在Forge服务端尝试过吗
> 
> 试了一下，好像也会这样，奇怪了，为啥呢

或许你可以试下实例化Screen对象？ 在服务端的注解, Screen被注解为@OnlyIn Client

**Comment by 3269199948** [comment]
> > > 在Forge服务端尝试过吗
> > 
> > 
> > 试了一下，好像也会这样，奇怪了，为啥呢
> 
> 或许你可以试下实例化Screen对象？ 在服务端的注解, Screen被注解为@onlyin Client


有点操蛋，必须上  
        @OnlyIn(Dist.CLIENT)  才行
