### ISSUE TITLE
会更新到1.18吗

### ISSUE THREAD

**Issue by 3269199948** [Loli-Server/LoliServer1.16#295]
**Is your Suggestion related to a problem? Please describe.(建议是否与问题有关？请描述)**

**Describe the solution you'd like(描述你想要的解决方案)**

**Additional context(附加)**
如题 !

**Comment by ljt1477059273** [comment]
已经再开发了 不要急

**Comment by XionioXMaster** [comment]
随着时间的推移

**Comment by Kotori0629** [comment]
开发中
