### ISSUE TITLE
[1.16] WorldGuardRegionProtect 0.7.0 plugin

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#296]
**Minecraft Version(我的世界版本) :** 1 16
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "[LoliServer-1.16.5-************-server.jar](https://github.com/Loli-Server/LoliServer1.16/actions/runs/1560505749)"

**Operating System(操作系统) :** unbuntu 20

**Concerned mod / plugin(有关的插件/Mod) :** [Provide mod / plugin name and download link if possible](https://github.com/RitaSister/WorldGuardRegionProtect/releases/tag/0.7.0) 1.13-1.17 [0.7.0] 

**Logs :** [Link(s) of logs and crash reports if you have,](https://gist.github.com/XionioXMaster/48b29f5f5f7c2c4b1e20e533886b0351) (https://paste.loliidc.cn)

**Steps to Reproduce(复现步骤) :**
 1. dowload, isntall to server
 2. start

**Comment by Kotori0629** [comment]
Try : re-gen config.yml

**Comment by RitaSister** [comment]
Why people don't send issue's to me Author? :c

**Comment by RitaSister** [comment]
@XionioXMaster please update to 0.7.1-pre3 https://github.com/RitaSister/WorldGuardRegionProtect/releases/tag/0.7.1-pre3
I releasing for oldest version (java 11 for MC 1.13-1.16) and (java 16 for MC 1.17-1.18)

**Comment by Kotori0629** [comment]
> @XionioXMaster please update to 0.7.1-pre4 https://github.com/RitaSister/WorldGuardRegionProtect/releases/tag/0.7.1-pre4 I releasing for oldest version (java 11 for MC 1.13-1.16) and (java 16 for MC 1.17-1.18)

Thank~

**Comment by leonpano2006** [comment]
> @XionioXMaster please update to 0.7.1-pre4 https://github.com/RitaSister/WorldGuardRegionProtect/releases/tag/0.7.1-pre4
> 
> I releasing for oldest version (java 11 for MC 1.13-1.16) and (java 16 for MC 1.17-1.18)

Is better java17 for MC 1.17-1.18
Java16 is unsupported (outdated)
