### ISSUE TITLE
禁用Log4j2查询器与修正Log4j2拦截正则表达式 1.16.5 CI with Gradle #481

### ISSUE THREAD

**Issue by Gu-f** [Loli-Server/LoliServer1.16#297]
该构建版本无法正常启动
仅仅输出了一些info信息，并没有启动
等待修复Log4j2后的release版本

**Comment by Kotori0629** [comment]
请附上logs, 185之后版本的变动为：只允许JDK11运行

**Comment by Gu-f** [comment]
如果是只允许jdk11运行我想我知道为啥了，因为之前的正式版本是用的java8运行的。如果是jdk11运行的话运行1.16.5会收到影响吗，我记得1.16.5需要8才能运行。

**Comment by Kotori0629** [comment]
> 如果是只允许jdk11运行我想我知道为啥了，因为之前的正式版本是用的java8运行的。如果是jdk11运行的话运行1.16.5会收到影响吗，我记得1.16.5需要8才能运行。

应该不会哦，但是装有虚无世界3的服务器将无法加入服务器

**Comment by Gu-f** [comment]
是的我刚刚试了，虚无3会无法运行，作者方便找个时间修复下这个问题吗。虚无3只支持java8，我的服务端有虚无3，这。。。

**Comment by Kotori0629** [comment]
> 是的我刚刚试了，虚无3会无法运行，作者方便找个时间修复下这个问题吗。虚无3只支持java8，我的服务端有虚无3，这。。。

尽快恢复JDK8运行

**Comment by Gu-f** [comment]
十分感谢！

**Comment by Kotori0629** [comment]
> 十分感谢！

已修正

**Comment by LaDerek** [comment]
Ало, где фикс сука?

**Comment by Kotori0629** [comment]
> Ало, где фикс сука?

In Action
