### ISSUE TITLE
错误反馈：启动时报错

### ISSUE THREAD

**Issue by kurisucat** [Loli-Server/LoliServer1.16#298]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 25c80aa

**Operating System(操作系统) :** Windows Server® 2012 R2

**Logs :** https://paste.loliidc.cn/?16c8483ac5c0d0a6#7URXeCxVXb2GRUqs1R6QbievLMUc66oYyywmB9Jf4F1T

**Mod list(模组列表) :** nothing

**Plugin list(插件列表) :** nothing

**Description of issue(描述) :** 在启动的时候报错，是新建的服务器。 JDK11

**Comment by Xplodin** [comment]
thats not jdk11 lol

**Comment by Kotori0629** [comment]
Use this: https://github.com/Loli-Server/LoliServer1.16/actions/runs/1569474584

**Comment by kurisucat** [comment]
> thats not jdk11 lol

jdk11 also same :/

**Comment by kurisucat** [comment]
> Use this: https://github.com/Loli-Server/LoliServer1.16/actions/runs/1569474584

thx, i try it. it is WORKING.
谢谢你，我试了，它 **正在工作** 。
感谢你的帮助
