### ISSUE TITLE
[1.16] JDK16 runtime caused ASM issue

### ISSUE THREAD

**Issue by Sam-Chai** [Loli-Server/LoliServer1.16#299]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** latest build (221)

**Operating System(操作系统) :** windows 10

**Logs :** {Link(s) of logs and crash reports if you have}, [(https://paste.loliidc.cn)](https://paste.loliidc.cn/?d0e91c7df68b24a4#8Pn2rqRQcvJRJx92j3X75urFtTtVJ7LT7WLq1mSMjCfL)

**Description of issue(描述) :** 
all of plugins doesn't load on jdk16 runtime. it seems like ASM problem.
now more and more plugins only support jdk16, like oraxen. so the server should upgrade it at time.
please fix it at time

**Comment by KomiMoe** [comment]
fixed
