### ISSUE TITLE
[1.16] WorldEdit Plugin. Problem with the "//regen" command

### ISSUE THREAD

**Issue by xniki119x** [Loli-Server/LoliServer1.16#300]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** "LoliServer-1.16.5-a6ee0e1-server.jar"

**Operating System(操作系统) :** Win10x64

**Concerned mod / plugin(有关的插件/Mod) :** [WorldEdit 7.2.8](https://dev.bukkit.org/projects/worldedit/files/3559523)

**Logs :** (https://paste.loliidc.cn/?c65cb666ed72d1e4#Fnfjdrr8VgErN3gbYv91PUvdJZAZdV5eekmpVExCpdxG)

**Steps to Reproduce(复现步骤) :**
 1. Start server with plugin WorldEdit
 2. Join the server
 3. Give yourself a permissions
 4. Select area, e.g. input command "//chunk"
 5. Input command "//regen"

**Description of issue :** When using the "//regen" command to regenerate the territory, an error occurs "java.lang.NoSuchMethodError: net.minecraft.world.storage.SaveFormat.c(Ljava/lang/String;Lnet/minecraft/util/RegistryKey;)Lnet/minecraft/world/storage/SaveFormat$LevelSave;"

**Comment by Kotori0629** [comment]
在 #306 中这个问题被修复, 但他仍然不可用, 原因是没有完整的写入nms patch, 等待解决

**Comment by KomiMoe** [comment]
fixed

**Comment by xniki119x** [comment]
Hi, glad you fixed this bug and now this command is working in the normal world, but there is another problem: This only works in the normal world, in other worlds like Hell, and another error appears attached to the file.
[latest.log](https://github.com/Loli-Server/LoliServer1.16/files/7776938/latest.log)

**Comment by Kotori0629** [comment]
> Hi, glad you fixed this bug and now this command is working in the normal world, but there is another problem: This only works in the normal world, in other worlds like Hell, and another error appears attached to the file. [latest.log](https://github.com/Loli-Server/LoliServer1.16/files/7776938/latest.log)

Reissue an issue

**Comment by KomiMoe** [comment]
fixed
