### ISSUE TITLE
Loliserver使用 机械动力官方整合包时崩溃

### ISSUE THREAD

**Issue by LittleHed** [Loli-Server/LoliServer1.16#301]
**Minecraft Version(我的世界版本) :** {1.16.5}

**LoliServer buildVersion(构建版本) :** {LoliServer-1.16.5-cf698da-server.jar}

**Operating System(操作系统) :** {Windows 10}

**Logs :** {[Link(s) of logs and crash reports if you have](https://paste.loliidc.cn/?972eecd9e99fb746#H7NAvkAT1JJqw5H2WP3ydXBQTzvjPRm2EEyNEkN1c8Cs)}, (https://paste.loliidc.cn)

**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
见描述
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
无
**Description of issue(描述) :** {
整合包链接：（使用v1.3最新版本），模组列表在介绍贴有
https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond
安装以下汉化包：http://www.bilibili.com/read/cv13821073
服务端安装loliserver，进入服务器后jei搜索导航电脑，按思索搭建多方块火箭结构，构建后服务器崩溃，后台无报错}

**Comment by Kotori0629** [comment]
https://github.com/Loli-Server/LoliServer1.16/actions/runs/1595790752 等待这个Action执行完毕，尝试使用该Action下上传的构建

**Comment by LittleHed** [comment]
经测试该构建能正常使用高级火箭
