### ISSUE TITLE
MOD不符合

### ISSUE THREAD

**Issue by 3269199948** [Loli-Server/LoliServer1.16#303]
当客户端和服务端MOD不符合时，提供一个配置文件配置提示信息

可以实现吗

**Comment by Kotori0629** [comment]
或许可以

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/146666846-74f6b45e-9d74-48fe-8a77-c3ed072f6721.png)
其实一直都有

**Comment by 3269199948** [comment]
> ![image](https://user-images.githubusercontent.com/81866089/146666846-74f6b45e-9d74-48fe-8a77-c3ed072f6721.png) 其实一直都有

这个在哪里可以配置

**Comment by Kotori0629** [comment]
> 

默认都有啦
