### ISSUE TITLE
Crash (1.16)

### ISSUE THREAD

**Issue by ImMAils** [Loli-Server/LoliServer1.16#304]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 185

**Operating System(操作系统) :** Ubuntu

**Logs :** {Link(s) of logs and crash reports if you have}, https://paste.ubuntu.com/p/jtGCYgrZ8W/

**Mod list(模组列表) :** Presented in crash log

**Plugin list(插件列表) :** BanItem, ClearLag, SmoothSleep, NametagHide, AutoShutdown, LightPerms, SkinsRestorer, LWP, PlaceholderAPI, SimpleSit, DiscordSRV

**Description of issue(描述) :** Maybe a fish bug when it swims from the island in the sky, where water falls to the ground (Salmons spawning in this water)

**Comment by Kotori0629** [comment]
I suspect this is a forge bug
