### ISSUE TITLE
[1.16] Wyrmroost 中蝶形利维坦与皇家血色影响tps问题

### ISSUE THREAD

**Issue by Theagree** [Loli-Server/LoliServer1.16#308]
**Minecraft Version(我的世界版本) :** Minecraft version
1.16.5forge 36.2.22
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-******-server.jar"
LoliServer-1.16.5-eac7eaf-server
**Operating System(操作系统) :** Provide the name of your OS
windows 10
**Concerned mod / plugin(有关的插件/Mod) :** Provide mod / plugin name and download link if possible
Wyrmroost
**Logs :** Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)
不会崩服
**Steps to Reproduce(复现步骤) :**
 1. 拿出蝶形利维坦刷怪蛋
 2. 在水中放置
1.拿出皇家血色刷怪蛋
2.在地面放置

**Description of issue :** Give all details about your issue
我认为卡顿出现在这两只怪寻找目标时，tps严重降低。mod版本1.2.11

**Comment by Kotori0629** [comment]
FPS问题为啥会和服务端有关

**Comment by Theagree** [comment]
是tps不是fps

**Comment by Kotori0629** [comment]
和端无关，我不管你使用的配置，和我没关系的

**Comment by Theagree** [comment]
可是在单机里没问题的

**Comment by Kotori0629** [comment]
> 可是在单机里没问题的

你在单机你都不知道你当时mspt有多少

**Comment by ljt1477059273** [comment]
可能是你服务器配置太拉了 去找群主租个5900X 10850K吧
