### ISSUE TITLE
问题较多，写在下面。

### ISSUE THREAD

**Issue by Theagree** [Loli-Server/LoliServer1.16#33]
刷铁机不刷铁傀儡，草方块不蔓延，地狱僵尸猪人不会被海龟蛋吸引同时不会新出生的猪人不会继承老猪人仇恨。最后是主世界地狱门不刷猪人

**Comment by Theagree** [comment]
主世界地狱门刷了。。

**Comment by Theagree** [comment]
去其他世界后再回主世界地狱门就不刷猪人了，必须要重新点亮才可以

**Comment by Kotori0629** [comment]
These problems may be due to incomplete NMS patch , Wait LoliServer update.

**Comment by Kotori0629** [comment]
> 刷铁机不刷铁傀儡，草方块不蔓延，地狱僵尸猪人不会被海龟蛋吸引同时不会新出生的猪人不会继承老猪人仇恨。最后是主世界地狱门不刷猪人

已在最新版本修复
