### ISSUE TITLE
Valhelsia Structure Crash

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Loli-Server/LoliServer1.16#34]
When using the latest version of Valhelsia structure's it crashes LoliServer, Using the latest GitHub build and GitHub release build crashes it

[latest.log](https://github.com/Loli-Server/LoliServer/files/6528042/latest.log)

**Comment by Kotori0629** [comment]
This problem may not be fixed in time, Because this mod uses ASM to modify the server

**Comment by SirOMGitsYOU** [comment]
Ah okay hopefully this is something that can be fixed, I can try re-naming the mod so it is loaded in last?

**Comment by Kotori0629** [comment]
> Ah okay hopefully this is something that can be fixed, I can try re-naming the mod so it is loaded in last?
> 
> Edit: nope still didn't fix it

It's hard to fix. I may not close commit until it is fixed.
