### ISSUE TITLE
EssentialsX / CMI 与LuckPerms ， 及 世界难度 difficulty 调整

### ISSUE THREAD

**Issue by KMRuri** [Loli-Server/LoliServer1.16#43]
装有权限插件LuckPerms时，
当玩家死亡，重生后，会导致/spawn和/back指令失效（其他指令暂未发现故不确定是否还有更多的失效指令）
并且重生后切成创造模式，怪物依然对玩家有仇恨，同时可以在创造模式下被怪物打死或从高空摔死或被岩浆烫死。（推测其他游戏模式对应的特性可能都会有失效一部分）
目前只能死亡重生后，断开服务器连接重上解决问题。

_(:з」∠)_

**Comment by KMRuri** [comment]
更新：
该问题会发生在最新版本 LuckPerms-Bukkit-5.3.3
旧版本 LuckPerms-Bukkit-5.3.1不会发生该问题

**Comment by Kotori0629** [comment]
Retry replace EssentialsX to CMI

**Comment by KMRuri** [comment]
> 
> 
> Retry replace EssentialsX to CMI

更新：
使用截至目前最新版本的 paper-1.16.5-762 与 LoliServer-1.16.5-83b9fa6-server
在LoliServer测试，CMI与LuckPerm不会出现上述问题。
但会导致/cmi dback失效，提示无坐标地点，应该是无法记录死亡地点，单独测试CMI，这个问题依然存在。
在paper测试无上述问题，能够正确记录坐标地点使/cmi dback生效。

补充问题：
无法单独调整某个世界的难度，调整难度将会被直接全局应用。
即使使用Multiverse在配置中修改世界难度依然无效，会被强制改回之前的难度。
使用Multiverse /mv import 某个世界时，该世界的默认难度也会被全局应用到所有世界。

**Comment by Kotori0629** [comment]
OK. wait fix
