### ISSUE TITLE
村民无限扔食物

### ISSUE THREAD

**Issue by AntsandIce** [Loli-Server/LoliServer1.16#46]
在最新服务端LoliServer-1.16.5-83b9fa6-server中 村民出现了无限扔食物的问题
玩家的反馈:
"正常来说，村民繁殖，是需要他们持有食物
费劲的办法就是，人工扔给村民食物
自动化就是，给村民农夫转职
这样农夫就会自己收菜种菜
然后，当他们需要繁育的时候，农夫就会把食物扔给另一个村民，这样两只都有食物，下一步就是繁育了
但是服务器不知道为什么，会一直扔
理论上来说，农夫扔食物，够吃就行"

查看原版wiki过后 确定是bug了...

**Comment by Kotori0629** [comment]
hmm. 我没法复现这个 Bug
