### ISSUE TITLE
我试便所有死亡绑定插件，均无效

### ISSUE THREAD

**Issue by DevilJueChen** [Loli-Server/LoliServer1.16#47]
这里随便带一个绑定插件

插件名称：DreamBind/梦绑定
插件下载直链：https://www.mcbbs.net/thread-1177911-1-1.html
使用服务端核心构建版本：[谨慎使用]LoliServer-1.16.5-83b9fa6-server
是否拥有前置(需附上前置下载链接)：无前置
崩溃/错误报告：https://paste.ubuntu.com/p/dvzfszwxjt/
复现方式：使用死亡不掉落绑定绑定物品后死亡

**Comment by Kotori0629** [comment]
Bukkit don't have getEntitySpawnReason() method

**Comment by Kotori0629** [comment]
请联系作者, LoliServer并没有完全支持Paper

**Comment by Kotori0629** [comment]
[LoliServer-1.16.5-UNKNOW-server](http://download.loliidc.cn/LoliServer-1.16.5-UNKNOW-server.jar)

**Comment by Kotori0629** [comment]
Fixed this problem, But don't use this method. Please!
