### ISSUE TITLE
[1.16]无法进入下界

### ISSUE THREAD

**Issue by chipspvp** [Loli-Server/LoliServer1.16#55]
无法进入下界，如题
核心版本:1.16.5
系统:win10，win7。VPS的系统是winwods2016 server
游戏版本1.16.5
插件列表:[权限]LuckPerms
[基础]SunLight
[成就]AdvancedAchievements
[登录]AuthMe
[拍卖行]AuctionHouse
[血月]bloodmoon
[NPC]Citizens
[NPC指令]CitizensCMD
[横幅]ColorMOTD
[垃圾桶]ClearItem	
[在线奖励]CtOnlineReward
[抽奖箱]GoldenCrates
[好友]GoodFriends
[全息图]HolographicDisplays	
[红石音乐]jukebox	
[签到]LiteSignIn
[多世界]Multiverse-Core
[赏金猎人]MoneyHunters
[称号]PlayerTitle
[地皮]PlotSquared
［点卷]PlayerPoints
[箱子商店]QuickShop
[领地]Residence
[pvp]SimplePasiveMode
[菜单]TrMenu
[计分版]TitleManager
[会员管理]VipSystem
[创世神]worldedit
[区域保护]worldguard	
[点歌]ZMusic
mods列表:
音乐模组 ALLMusic            
[小地图]Voxelmap
[更多箱子]ironchest
[前置]citadel
[龙之息]Wyrmroosta	
[生物]alexsmobs
[作物]Croptopia
其实就是mcbbs上那个萝莉生存的服务端
![-1be783eada0a2644](https://user-images.githubusercontent.com/86564083/123550649-27be8280-d734-11eb-8903-ff2d2566a3ae.png)

**Comment by Luohuayu** [comment]
无MOD且只安装Ess插件的情况可以正常进入下界
![2021-06-28_19 00 17](https://user-images.githubusercontent.com/29095770/123626199-262fb000-d843-11eb-8797-5f111766940b.png)

**Comment by Kotori0629** [comment]
请检查是否为在world主世界开启地狱门
