### ISSUE TITLE
玩家进入地狱时有概率崩溃

### ISSUE THREAD

**Issue by TCwater** [Loli-Server/LoliServer1.16#57]
**Minecraft Version(我的世界版本) :** {Minecraft version}
1.16.5
**LoliServer buildVersion(构建版本) :** {Provide LoliServer build number}
LoliServer-1.16.5-38-server
**Operating System(操作系统) :** {Provide the name of your OS}
Windows Server 2008 R2 Enterprise
**Logs :** {Link(s) of logs and crash reports if you have}
https://paste.ubuntu.com/p/dV6RFwj6Bx/
**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
【/getmodlist这个指令也用不了】https://paste.ubuntu.com/p/RXmhjhMXsk/
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
https://paste.ubuntu.com/p/hqQzpz9qFp/
**Description of issue(描述) :** {Give all details about your issue}
玩家进入地狱时有概率崩溃

**Comment by Luohuayu** [comment]
https://github.com/garet90/simple-skyblock/blob/master/skyblock/src/holiday/garet/skyblock/world/Generator.java#L56-L60
SimpleSkyblock插件不支持1.16
