### ISSUE TITLE
[1.16] Shopkeeper创建NPC商店无法交易

### ISSUE THREAD

**Issue by 3269199948** [Loli-Server/LoliServer1.16#59]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-38-server.jar"

**Operating System(操作系统) :** Centos7.5

**Concerned mod / plugin(有关的插件/Mod) :** 没有MOD，插件只有一个Shopkeepers-2.12.0.jar

**Logs :** 没有任何日志

**Steps to Reproduce(复现步骤) :**
 1. 将插件放入plugins中
 2. 启动服务器
 3. 使用/shopkeeper创建一个NPC，shift+右键 编辑NPC，随便放点啥，然后关闭界面，拿着物品去交换，界面会直接关闭。在Spigot中不会出现此问题

**Comment by Kotori0629** [comment]
在三个月前就已经提交过的问题. 这个Bug没有被得到解决, 某些核心代码被改变
