### ISSUE TITLE
I don't understand this bug

### ISSUE THREAD

**Issue by myungeo** [Loli-Server/LoliServer1.16#60]
![image](https://user-images.githubusercontent.com/87235787/125166417-765d2980-e1d6-11eb-8067-b810e107ea92.png)Minecraft Version(我的世界版本) :1.16.5 {Minecraft version}

**LoliServer buildVersion(构建版本) :LoliServer-1.16.5-38-server {Provide LoliServer build number}

**Operating System(操作系统) :window10 {Provide the name of your OS}

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list(模组列表) :
![image](https://user-images.githubusercontent.com/87235787/125166383-647b8680-e1d6-11eb-99c5-c68f50f6dc1e.png)
 {List of your mods. You can also use /getmodlist command on your server}

**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}

![image](https://user-images.githubusercontent.com/87235787/125166417-765d2980-e1d6-11eb-8067-b810e107ea92.png)

Description of issue(描述) :An error occurs with the server start. You can ask for help to the LoliServer support on GitHub.
 {Give all details about your issue}

**Comment by Kotori0629** [comment]
I think you can see these error in debug.log. Kill the JVM virtual machine process and try again
