### ISSUE TITLE
CDN is not accesible

### ISSUE THREAD

**Issue by wtlgo** [Loli-Server/LoliServer1.16#61]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-38-server

**Operating System(操作系统) :** It's shared hosting, I don't know the OS ¯\_(ツ)_/¯

**Logs :** https://hastebin.com/alatiyipod.properties

**Mod list(模组列表) :** I don't think it's relevant to the issue, but I'll provide it later if it's important.

**Plugin list(插件列表) :** I don't think it's relevant to the issue, but I'll provide it later if it's important.

**Description of issue(描述) :** I believe that `http://nat.loliidc.cn:33741` is down for some reason

**Comment by MrJexes** [comment]
I have the same ;) 
Operating System: Ubuntu 20.04
![image](https://user-images.githubusercontent.com/70405213/125193391-4442da80-e25d-11eb-8331-3a748fdc2e56.png)

**Comment by BTXueLi** [comment]
![W)MDBQ@Y19HJD7M1B(BT}64](https://user-images.githubusercontent.com/86368368/125212404-bfe56b80-e2df-11eb-9283-cb413c7d15f2.png)
me too
centos8.2

**Comment by EvilToasterDBU** [comment]
windows 11 dev 22000.65
![image](https://user-images.githubusercontent.com/15957247/125273305-12894c80-e30d-11eb-96ad-ccecd810a964.png)

**Comment by EvilToasterDBU** [comment]
I slove it
1. Change setting in `loliserver.yml ` to `check-update: false`
2. Download and unpack [libraries](https://drive.google.com/file/d/1tYJV8xbx5XlCKs_GT9u0si59iLisj_u8/view?usp=sharing)
3. You can run server
Enjoy 🍭

**Comment by Kotori0629** [comment]
Set check-update: false and check_libraries: false in loliserver.yml. our update server and download server have been repaired due to hardware failure

**Comment by Kotori0629** [comment]
Sorry for the inconvenience
