### ISSUE TITLE
bukkit error

### ISSUE THREAD

**Issue by ehrud9412** [Loli-Server/LoliServer1.16#62]
**Minecraft Version(我的世界版本) :** {Minecraft version} 1.16.5 forge

**LoliServer buildVersion(构建版本) :** {Provide LoliServer build number} 1.16.5-38

**Operating System(操作系统) :** {Provide the name of your OS} Windows 10

**Logs :** {Link(s) of logs and crash reports if you have}

.____          .__  .__  _________
|    |    ____ |  | |__|/   _____/ ______________  __ ___________
|    |   /  _ \|  | |  |\_____  \_/ __ \_  __ \  \/ // __ \_  __ \
|    |__(  <_> )  |_|  |/        \  ___/|  | \/\   /\  ___/|  | \/
|_______ \____/|____/__/_______  /\___  >__|    \_/  \___  >__|
        \/                     \/     \/                 \/
                             Welcome to LoliServer 1.16.5 ! - LoliServer Developement Group

[11:09:36][Loli/]: The Java version verification is completed, and the LoliServer process will continue
An error occurs with the server start. You can ask for help to the LoliServer support on GitHub.

**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
doesn't matter
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
doesn't matter
**Description of issue(描述) :** {Give all details about your issue}
To restart the server, enter the stop command and try to restart the server, but only the command appears repeatedly. What's the problem?
![캡처](https://user-images.githubusercontent.com/71758043/125221294-faaccb00-e302-11eb-8760-05c2c1f5b29b.PNG)

I

**Comment by 3269199948** [comment]
disable server check update

**Comment by Kotori0629** [comment]
Please kill java.exe or JVM virtual machine process and restart it
