### ISSUE TITLE
[1.16] When a player dies, the DiscordSrv plugin cannot pick up any information about it. (Bonus: The One Probe error)

### ISSUE THREAD

**Issue by EvilToasterDBU** [Loli-Server/LoliServer1.16#63]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-Unknown-f5b8574-server.jar"

**Operating System(操作系统) :** Windows Server 2019

**Concerned mod / plugin(有关的插件/Mod) :** [DiscordSRV Build 1.23.0](https://www.curseforge.com/minecraft/bukkit-plugins/discordsrv/files/3352722), [The One Probe 3.1.4](https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files/3319255)

**Logs :** https://pastebin.com/W5pHbGNZ

**Steps to Reproduce(复现步骤) :**
 1. Player dies
 2. DiscordSRV listens and cannot hear information about death
 3. DiscordSRV Doesn't write death message on Discord 
 3. Error
 
**Description of issue :** 
DiscordSRV: Described above 
The One Probe: I dont know

**Comment by Kotori0629** [comment]
![QQ图片20210713141133](https://user-images.githubusercontent.com/81866089/125400263-45524400-e3e4-11eb-8a53-f2b49ef02853.png)
I think you can refer to this.

**Comment by Kotori0629** [comment]
You can try the latest version of LoliServer ?

**Comment by EvilToasterDBU** [comment]
My build before [this commit](https://github.com/Loli-Server/LoliServer1.16/commit/1dc08431d8bd874d5332cee486f52cac8aab5abb).
I can try the latest build later.

**Comment by Kotori0629** [comment]
Okay, I try it

**Comment by Kotori0629** [comment]
I tested the plug-in, but there was no exception when using it. My country will block the API of the plug-in, so I can't test it. Your error report indicates that your name can't exceed 256 characters, please check and try again

**Comment by isKONSTANTIN** [comment]
I also ran into some problems after the death of the player: the EssentialsX plugin starts to behave strangely. The /gm or /gamemode commands do not work correctly. The game mode seems to change, but in creative the damage goes away, you can't take items, and you can't break blocks either. It looks like the server just doesn't seem to know that the game mode has changed.

If necessary, I can shoot a video

**Comment by Kotori0629** [comment]
> I also ran into some problems after the death of the player: the EssentialsX plugin starts to behave strangely. The /gm or /gamemode commands do not work correctly. The game mode seems to change, but in creative the damage goes away, you can't take items, and you can't break blocks either. It looks like the server just doesn't seem to know that the game mode has changed.
> 
> If necessary, I can shoot a video

![QQ图片20210713141133](https://user-images.githubusercontent.com/81866089/125447609-9e668bd3-134d-46c2-8990-7c2970fe6861.png)
I want this screenshot to tell you why

**Comment by isKONSTANTIN** [comment]
> > I also ran into some problems after the death of the player: the EssentialsX plugin starts to behave strangely. The /gm or /gamemode commands do not work correctly. The game mode seems to change, but in creative the damage goes away, you can't take items, and you can't break blocks either. It looks like the server just doesn't seem to know that the game mode has changed.
> > If necessary, I can shoot a video
> 
> After Player re-join, Will these problems still exist？

No, after re-join everything is ok

**Comment by Kotori0629** [comment]
> > > I also ran into some problems after the death of the player: the EssentialsX plugin starts to behave strangely. The /gm or /gamemode commands do not work correctly. The game mode seems to change, but in creative the damage goes away, you can't take items, and you can't break blocks either. It looks like the server just doesn't seem to know that the game mode has changed.
> > > If necessary, I can shoot a video
> > 
> > 
> > After Player re-join, Will these problems still exist？
> 
> No, after re-join everything is ok

Yes, There is an issue about the plotsquared plug-in, which is unable to return to plot after the player's death. This is also the same reason

**Comment by isKONSTANTIN** [comment]
Sadly(((

**Comment by EvilToasterDBU** [comment]
> I tested the plug-in, but there was no exception when using it. My country will block the API of the plug-in, so I can't test it. Your error report indicates that your name can't exceed 256 characters, please check and try again

I'm not sure exactly, but I think the problem is in [this file](https://github.com/Loli-Server/LoliServer1.16/blob/1.16.5/patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch), I searched for the "death message" in your core and Mohist core (where the plugin works fine under the same conditions), and found this [lines there ](https://github.com/MohistMC/Mohist/blob/03f1a5b868c73ea4a26bc18e15971819af531b7f/patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch#L870-L883), maybe this will help you, I to unfortunately I don't understand anything about this and I don't know how to add these lines myself to my build for the test 

Sorry if i'm wrong

**Comment by Kotori0629** [comment]
> > I tested the plug-in, but there was no exception when using it. My country will block the API of the plug-in, so I can't test it. Your error report indicates that your name can't exceed 256 characters, please check and try again
> 
> 
> 
> I'm not sure exactly, but I think the problem is in [this file](https://github.com/Loli-Server/LoliServer1.16/blob/1.16.5/patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch), I searched for the "death message" in your core and Mohist core (where the plugin works fine under the same conditions), and found this [lines there ](https://github.com/MohistMC/Mohist/blob/03f1a5b868c73ea4a26bc18e15971819af531b7f/patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch#L870-L883), maybe this will help you, I to unfortunately I don't understand anything about this and I don't know how to add these lines myself to my build for the test 
> 
> Or maybe [this ](https://github.com/MohistMC/Mohist/search?q=event+DeathMessage)help
> 
> 
> 
> Sorry if i'm wrong 
> 
> 

Of course, I also hope that the problem is in this plugin..

**Comment by EvilToasterDBU** [comment]
By the way, the current build did not change the situation naturally 😞

**Comment by Kotori0629** [comment]
> By the way, the current build did not change the situation naturally 😞

Ok

**Comment by EvilToasterDBU** [comment]
Fixed? no 😄 
```
[19:21:31] [Craft Scheduler Thread - 0/WARN] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] Plugin DiscordSRV v1.23.1-SNAPSHOT generated an exception while executing task 29
java.lang.IllegalArgumentException: Name cannot be longer than 256 characters.
	at github.scarsz.discordsrv.dependencies.jda.internal.utils.Checks.check(Checks.java:62) ~[?:?]
	at github.scarsz.discordsrv.dependencies.jda.api.EmbedBuilder.setAuthor(EmbedBuilder.java:621) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.translateMessage(DiscordSRV.java:1917) ~[?:?]
	at github.scarsz.discordsrv.listeners.PlayerDeathListener.runAsync(PlayerDeathListener.java:109) ~[?:?]
	at github.scarsz.discordsrv.listeners.PlayerDeathListener.lambda$onPlayerDeath$0(PlayerDeathListener.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_291]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
```
`This server is running LoliServer version 1.16.5-Unknown-4a27d92 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.35)`

**Comment by Kotori0629** [comment]
> Fixed? no 😄 
> 
> ```
> 
> [19:21:31] [Craft Scheduler Thread - 0/WARN] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] Plugin DiscordSRV v1.23.1-SNAPSHOT generated an exception while executing task 29
> 
> java.lang.IllegalArgumentException: Name cannot be longer than 256 characters.
> 
> 	at github.scarsz.discordsrv.dependencies.jda.internal.utils.Checks.check(Checks.java:62) ~[?:?]
> 
> 	at github.scarsz.discordsrv.dependencies.jda.api.EmbedBuilder.setAuthor(EmbedBuilder.java:621) ~[?:?]
> 
> 	at github.scarsz.discordsrv.DiscordSRV.translateMessage(DiscordSRV.java:1917) ~[?:?]
> 
> 	at github.scarsz.discordsrv.listeners.PlayerDeathListener.runAsync(PlayerDeathListener.java:109) ~[?:?]
> 
> 	at github.scarsz.discordsrv.listeners.PlayerDeathListener.lambda$onPlayerDeath$0(PlayerDeathListener.java:58) ~[?:?]
> 
> 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
> 
> 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
> 
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_291]
> 
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_291]
> 
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
> 
> ```
> 
> `This server is running LoliServer version 1.16.5-Unknown-4a27d92 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.35)`
> 
> 

I mean fix PlayerList error..
