### ISSUE TITLE
I don't know what happened

### ISSUE THREAD

**Issue by 3269199948** [Loli-Server/LoliServer1.16#66]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-38-server

**Operating System(操作系统) :** Centos7.5

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list(模组列表) :**  https://error-1254387167.cos.ap-chengdu.myqcloud.com/QQ%E6%88%AA%E5%9B%BE20210714202000.png

**Plugin list(插件列表) :** https://error-1254387167.cos.ap-chengdu.myqcloud.com/QQ%E6%88%AA%E5%9B%BE20210714202112.png

**Description of issue(描述) :** I don't know what happened

https://paste.ubuntu.com/p/33DmXCFkBg/

**Comment by Kotori0629** [comment]
Aoa3创建新区块时引起的异常， 尝试备份后删除相关世界
