### ISSUE TITLE
[1.16.5] Plugin remap error

### ISSUE THREAD

**Issue by bigenergy** [Loli-Server/LoliServer1.16#67]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-38-server.jar"

**Operating System(操作系统) :**ubuntu

**Concerned mod / plugin(有关的插件/Mod) :** uskyblock https://www.spigotmc.org/resources/uskyblock-revived.66795/

**Logs :** https://paste.ubuntu.com/p/qR6HvMvF7v/

**Comment by Kotori0629** [comment]
Can we use betonbox + bskyblock? We have done compatible processing for betonbox
