### ISSUE TITLE
[1.16] Crash

### ISSUE THREAD

**Issue by EvilToasterDBU** [Loli-Server/LoliServer1.16#69]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-Unknown-fa7548e-server.jar"

**Operating System(操作系统) :** Windows Server 2019

**Concerned mod / plugin(有关的插件/Mod) :** Atum2?

**Logs :** https://hastebin.com/neyijezozo.yaml

**Steps to Reproduce(复现步骤) :**
 1. Dont know

**Description of issue :** Dont know

**Comment by Kotori0629** [comment]
Incomplete, please attach detailed steps to reproduce

**Comment by EvilToasterDBU** [comment]
[Another crash with the same problem](https://hastebin.com/oquzupolog.yaml)

According to our assumptions, the reason for the crash is the atum entity: `atum:villager_female`, which is trying to do something, it is not known for certain what exactly, sometimes it is enough just to load the location. In the crashlogs, there is a description of "Ticking entity". I don't understand logs well, that's why it's difficult for me to create a detailed description, I can only attach a log.

**Comment by Kotori0629** [comment]
I think you should contact the mod author
