### ISSUE TITLE
无法下载依赖文件

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [Loli-Server/LoliServer1.16#70]
**Minecraft Version(我的世界版本) :** {Minecraft version}
1.16.1
**LoliServer buildVersion(构建版本) :** {Provide LoliServer build number}
LoliServer-1.16.5-38-server
**Operating System(操作系统) :** {Provide the name of your OS}
Windows10专业版
**Logs :** {Link(s) of logs and crash reports if you have}
-------------------------------------------
        服务器启动中，关闭请输入stop
-------------------------------------------
.____          .__  .__  _________
|    |    ____ |  | |__|/   _____/ ______________  __ ___________
|    |   /  _ \|  | |  |\_____  \_/ __ \_  __ \  \/ // __ \_  __ \
|    |__(  <_> )  |_|  |/        \  ___/|  | \/\   /\  ___/|  | \/
|_______ \____/|____/__/_______  /\___  >__|    \_/  \___  >__|
        \/                     \/     \/                 \/
                             Welcome to LoliServer 1.16.5 ! - LoliServer Developement Group

[16:11:04][Loli/]: JAVA版本验证完成, LoliServer进程将继续进行
Global percentage >0%
Downloading file unsafe-0.2.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar failed :(
Global percentage >0%
Downloading file j2objc-annotations-1.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar failed :(
Global percentage >0%
Downloading file asm-commons-6.1.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/ow2/asm/asm-commons/6.1.1/asm-commons-6.1.1.jar failed :(
Global percentage >0%
Downloading file grossjava9hacks-1.3.3.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar failed :(
Global percentage >0%
Downloading file guava-25.1-jre.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar failed :(
Global percentage >0%
Downloading file trove-1.0.2.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/trove/trove/1.0.2/trove-1.0.2.jar failed :(
Global percentage >0%
Downloading file jansi-1.18.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/fusesource/jansi/jansi/1.18/jansi-1.18.jar failed :(
Global percentage >0%
Downloading file mcp_config-1.16.5-20210115.111550.zip with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip failed :(
Global percentage >0%
Downloading file eventbus-4.0.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar failed :(
Global percentage >0%
Downloading file json-simple-1.1.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar failed :(
Global percentage >0%
Downloading file accesstransformers-3.0.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar failed :(
Global percentage >0%
Downloading file jline-3.12.1.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar failed :(
Global percentage >0%
Downloading file forgespi-3.2.0.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar failed :(
Global percentage >0%
Downloading file log4j-iostreams-2.11.2.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/org/apache/logging/log4j/log4j-iostreams/2.11.2/log4j-iostreams-2.11.2.jar failed :(
Global percentage >0%
Downloading file commons-lang-2.6.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/commons-lang/commons-lang/2.6/commons-lang-2.6.jar failed :(
Global percentage >0%
Downloading file error_prone_annotations-2.1.3.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar failed :(
Global percentage >0%
Downloading file minecraft_server.1.16.5.jar with size -1 B
The download of http://nat.loliidc.cn:33741/libraries/minecraft_server.1.16.5.jar failed :(
Global percentage >0%
**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
None
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
![$FWJ(VIHAX0_48SCVJ3WSM](https://user-images.githubusercontent.com/79651409/126030828-f46d871a-ffd8-4567-b323-90f1c50170b1.png)

**Description of issue(描述) :** {Give all details about your issue}
无法下载，所有均无法下载

**Comment by XiaMoHuaHuo-CN** [comment]
我怀疑你站没了

**Comment by Kotori0629** [comment]
#61 重复
