### ISSUE TITLE
[1.16] Strange behavior of containers with mechanisms of the Create mod.

### ISSUE THREAD

**Issue by EvilToasterDBU** [Loli-Server/LoliServer1.16#72]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** "LoliServer-1.16.5-Unknown-fa7548e-server", "LoliServer-1.16.5-Unknown-4a27d92-server"

**Operating System(操作系统) :** Windows 11 21H2 (22000.71), Windows Server 2019 1809 (17763.1757)

**Concerned mod / plugin(有关的插件/Mod) :** [Create 1.16.5_v0.3.1c](https://www.curseforge.com/minecraft/mc-mods/create/files/3278516), [Create 1.16.5_v0.3.2b](https://www.curseforge.com/minecraft/mc-mods/create/files/3386319) (v0.3.2b Requirement [Flywheel mod](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3389159))

**Logs :** Nothing happens in the logs 

**Steps to Reproduce(复现步骤) :**
1. Build a mechanism with a container (for example a tree farmer)
2. Put items in the container
3. Start the mechanism
4. Stop the mechanism
5. Open the container, it will be empty 

**Description of issue :** Strange behavior of containers with mechanisms of the Create mod.
When the running mechanism of the mechanism stops, the objects from the containers disappear. But if you unload the containers of the mechanism without stopping it, then it gives them away. It was clearly shown for an example on the mechanism of a tree farmer, but this happens with any mechanism, be it a spinning one, moving on a piston, or a building on a minecart. 
I also tested this bug on vanilla forge 36.1.33. Everything works fine there.
[An illustrative example of the bug implementation is shown in the video. ](https://youtu.be/bjIocM68BBw)
_On video LoliServer-1.16.5-Unknown-4a27d92-server and Create 1.16.5_v0.3.2b_

_If you need to upload a video to another hosting, tell me about it (preferably with a link)_

**Comment by XionioXMaster** [comment]
Likewise, only I identified more problems!
https://github.com/Loli-Server/LoliServer1.16/issues/93
