### ISSUE TITLE
ProtocolLib和MythicMobs的错误

### ISSUE THREAD

**Issue by 3269199948** [Loli-Server/LoliServer1.16#75]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-38-server

**Operating System(操作系统) :** Win10

**Logs :**   https://paste.ubuntu.com/p/g4xCtXcZpy/
注意，这个日志我只截取了一部分，错误开始的时候截取的，如果需要完整的日志，联系我 ！

**Mod list(模组列表) :** 没有

**Plugin list(插件列表) :** Multiverse-Core-4.2.2、MythicLib-1.0.19、MythicMobs-4.12.0、ProtocolLib

**Description of issue(描述) :** 将插件加入服务器，启动服务器，进入主世界（world），随便玩不会出问题，使用mv创建一个世界，查看控制台，如果没有错误，尝试自杀、被怪物打死、被毒死或被火烧死，都有概率出现此异错误

如果你无法复现，我可以给你录制一个视频

**Comment by Kotori0629** [comment]
按理来说  已经修复了 ， 在我 发布的commit， 尚未构建/发布

**Comment by 3269199948** [comment]
那还不手动构建一个传到这里😁
