### ISSUE TITLE
[1.16] MMOcore+MMOitem+MythicLib运行问题

### ISSUE THREAD

**Issue by YKDZ** [Loli-Server/LoliServer1.16#76]
**Minecraft Version(我的世界版本) :1.16.5

**LoliServer buildVersion(构建版本) :LoliServer-1.16.5-38-server

**Steps to Reproduce(复现步骤) :**
 1. 安装这三个插件
 2. 进入游戏 死亡一次
 3. 使用/mi browse发现GUI失效（实际上该插件所有GUI都会失效）、MMOcore本身的属性加成生效等等... 基本这三个插件的所有功能都无法正常使用（无报错）
 4. 退出游戏重新进入问题消失，再次死亡问题复现

**Description of issue :无其它模组、插件进行了测试，在原生paper端测试没有发现问题

**Comment by Kotori0629** [comment]
已修复.. 但是构建站没有恢复.. 你可以自己构建

**Comment by Kotori0629** [comment]
#58 重复
