### ISSUE TITLE
Multiplayer game interface error

### ISSUE THREAD

**Issue by Rcrafte22** [Loli-Server/LoliServer1.16#79]
Minecraft Version :1.16.5

LoliServer buildVersion:LoliServer-1.16.5-38

Operating System :Windows 11

Concerned mod / plugin :Dynamic Lights and I18nUpdateMod

Logs : no logs

Steps to Reproduce :
1.Add one of these mods to the client

Description of issue :The multiplayer interface will indicate that FML is not compatible, but it can still enter the server normally
![error](https://user-images.githubusercontent.com/39120466/126433944-4ab603b9-155c-45a3-8ae1-0d1adb632dad.png)

**Comment by Kotori0629** [comment]
[https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/docs/NewFML.md](url)

**Comment by Kotori0629** [comment]
If your client mods is inconsistent with the server mods, this problem will recur and will not be solved
