### ISSUE TITLE
Failed download libraries

### ISSUE THREAD

**Issue by noremac09** [Loli-Server/LoliServer1.16#81]
![image](https://user-images.githubusercontent.com/25801549/126786133-1d1282d0-57a5-4eed-8a3d-5e4bf1cfd11c.png)

The latest build of the server from git cannot download the libraries when the server is first time started. Could you provide a archive with libraries, or fix the CDN?

**Comment by Kotori0629** [comment]
I will be fixed Jenkins Server on a few days.

**Comment by Kotori0629** [comment]
You can disable check-libraries optional in LoliServer.yml
