### ISSUE TITLE
[1.16] Alex's Mobs server crash

### ISSUE THREAD

**Issue by bigenergy** [Loli-Server/LoliServer1.16#85]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-38-server.jar"

**Operating System(操作系统) :** ubuntu

**Concerned mod / plugin(有关的插件/Mod) :** alexsmobs
**Logs :** https://paste.ubuntu.com/p/QNc8mm5nxQ/

**Comment by Kotori0629** [comment]
How can i repeat?

**Comment by bigenergy** [comment]
> How can i repeat?

Maybe spawn Tasmanian Devil from AlexsMobs

**Comment by Kotori0629** [comment]
I'll try

**Comment by XionioXMaster** [comment]
> I'll try

at com.github.alexthe666.alexsmobs.entity.EntityTasmanianDevil.func_70071_h_
This is on the side of the mod, you need to update the mod!

**Comment by bigenergy** [comment]
> > I'll try
> 
> at com.github.alexthe666.alexsmobs.entity.EntityTasmanianDevil.func_70071_h_
> This is on the side of the mod, you need to update the mod!

i'm use latest version, bro

alexsmobs-1.11.1

**Comment by XionioXMaster** [comment]
> > > I'll try
> > 
> > 
> > at com.github.alexthe666.alexsmobs.entity.EntityTasmanianDevil.func_70071_h_
> > This is on the side of the mod, you need to update the mod!
> 
> i'm use latest version, bro
> 
> alexsmobs-1.11.1
Very strange, I tried to reproduce it! I have an idea to set max-tick-time = -1
hello **GamePoint**
