### ISSUE TITLE
BentoBox空岛插件玩家死亡后指令失效

### ISSUE THREAD

**Issue by TCwater** [Loli-Server/LoliServer1.16#88]
**Minecraft Version(我的世界版本) :** Minecraft version
1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-******-server.jar"
LoliServer-1.16.5-Unknown-dbc0eae-server
**Operating System(操作系统) :** Provide the name of your OS
windows server 2019
**Concerned mod / plugin(有关的插件/Mod) :** Provide mod / plugin name and download link if possible
BentoBox-1.16.2 / BSkyBlock-1.14.4
**Logs :** Link(s) of logs and crash reports if you have
https://paste.ubuntu.com/p/B8jNgqPsf2/
**Steps to Reproduce(复现步骤) :**
 1. 创建岛屿
 2. 死亡
 3. 无法使用/is回到岛屿/管理员命令也无效
 4. 重新登录后才会恢复

**Description of issue :** Give all details about your issue
BentoBox空岛插件死亡后指令失效，使用spigot核心时该插件未出现该问题

**Comment by Kotori0629** [comment]
最新版本已经修复，等待构建站推送更新

**Comment by Kotori0629** [comment]
#58 Duplicate
