### ISSUE TITLE
[BuG 1.16.5] pls add .jar new

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#89]
I really like your kernel, please, could you download the latest build .jar with updated libraries? I don't know how to build java projects, help me.

**Comment by Kotori0629** [comment]
Can you wait two days? My build server is on its way!

**Comment by Kotori0629** [comment]
Thank you very much for your support and we will make persistent efforts

**Comment by GitJhopa** [comment]
ok

**Comment by GitJhopa** [comment]
and please update Forge

**Comment by XionioXMaster** [comment]
We are waiting for the fix . LOVE

**Comment by Kotori0629** [comment]
Fixed.
