### ISSUE TITLE
反馈不兼容mod

### ISSUE THREAD

**Issue by 1746813083** [Loli-Server/LoliServer1.16#90]
infernal-expansion-2.0.0 没有前置mod
valhelsia_structures-1.16.5-0.1.4 没有前置mod
这两个mod装入后 直接闪退
crash-reports文件夹里不会生成错误报告
求修复这两个mod

**Comment by Kotori0629** [comment]
有些问题无法被巧妙的去解决, 有极其暴力的方法可以修复, 但我无法那么去做
