### ISSUE TITLE
[1.16] Ishop plugin - Items that disappear into nowhere

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#94]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-38-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** Only Ishops

**Logs :** Nope

**Steps to Reproduce(复现步骤) :**
Install Ishops https://www.spigotmc.org/resources/ishop.84555/
Create a shop / shop create by hovering the cursor over the barrel, put a composter next to it so that there would be a storage.
Create a product, sometimes you need to update the cells several times as in the video below
https://youtu.be/htN7ChsN3c0

**Comment by KomiMoe** [comment]
iShop is only support 1.17

**Comment by KomiMoe** [comment]
this plugin works very well. you should buy it from other player.
