### ISSUE TITLE
[1.16] CM2E mod, crash

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#95]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-38-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** Only CM2E

**Logs :** Nope

**Steps to Reproduce(复现步骤) :**
Download CM2E https://github.com/ishlandbukkit/C2ME-forge/actions/runs/866624292
start the server

**Comment by Kotori0629** [comment]
Not Support
