### ISSUE TITLE
[1.16] infernal expansion crash server?

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#96]
**Minecraft Version(我的世界版本) :** 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-38-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** https://drive.google.com/file/d/1FBoz8pEbyPUjbz_QPR7ZATNgaS1z7MQC/view?usp=sharing

**Logs :** https://paste.ubuntu.com/p/X4jCnqjGbd/

**Steps to Reproduce(复现步骤) :**
 1. Install my mods and run server

**Description of issue :** After checking the error log, I believe that the problem is in the infernal-expansion mod

**Comment by XionioXMaster** [comment]
Removing the infernal expansion mod fixed the issue.

**Comment by MrJorman** [comment]
найс ядра меняешь + моды идеи у меня пиздишь, помойка

**Comment by XionioXMaster** [comment]
> найс ядра меняешь + моды идеи у меня пиздишь, помойка

Это кто у кого пиздит, ты видел свою помойку? Когда там вообще открытие?

**Comment by Kotori0629** [comment]
emm. Some bugs can't be repaired skillfully, but there are extremely violent methods)

**Comment by MrJorman** [comment]
fix pls.
